### ISSUE TITLE
Backpacks destroying items

### ISSUE THREAD

**Issue by srs-bsns** [gr8pefish/IronBackpacks#10]
Version: Iron Backpacks-1.7.10-1.1.2-universal

If a backpack is equiped after creation, without first being opened atleast once from the hotbar, any items put into it will disappear when the GUI closes.

If the backpack is opened atleast once from the hotbar before equiping it, it seems to function properly, or if the backpack is upgraded to the next tier it seems to function properly.

Under normal circumstances, this would only affect the basic backpack, however, if an iron, gold, or diamond backpack is cheated in then it too will experience the bug and start destroying items until it is opened from the hotbar or upgraded if possible.

Regards,
~~Modding is srs bsns.~~

**Comment by gr8pefish** [comment]
Thanks for the detailed report. I removed 1.1.2 from curse as it had some other errors, when I put it back up this error should be fixed.
