### ISSUE TITLE
Feature Request: Item collection SFX upon backpack collection

### ISSUE THREAD

**Issue by ribbanya** [gr8pefish/IronBackpacks#100]
Currently, when a backpack picks up a stack of items via its filter, the absorption sound effect normally present when picking up an item in Minecraft is circumvented. The mod would feel more polished if it were able to replicate it.

**Comment by gr8pefish** [comment]
Implemented in the latest version (2.2.14). 

I really can't close issues via commit messages today. [Added in commit a864042]
