### ISSUE TITLE
Low tier backpack problem with nest

### ISSUE THREAD

**Issue by Killaheala** [gr8pefish/IronBackpacks#101]
Iron Backpacks: 2.2.13
MC: 1.10.2
Forge: 2121

Okay this is what i found:

You have 1 main backpack made of iron (iron backpack) with nest upgrade, inside this main backpack you have 9 backpacks, 3 gold backpack and 6 iron backpack.

When you right click the main backpack on your hand you access to the other backpacks inside that works fine, if you right click another backpack iron or gold inside this backpack you can access to the backpacks normally, the problem comes when, you access a gold backpack inside the mainbackpack and then rightclick on the main backpack the game crashes, but if you access another iron backpack and then right click on the main backpack it goes back to the mainbackpack inventory, so saying simple, you cant go back to a main backpack if its a lower tier than the backpack inside the main you just accessed.

**Comment by Hazerd** [comment]
I can't seem to reproduce this, do you have any more details you can provide?
- Are you using a modpack? If so, which? If not, which other mods do you have installed?
- Do any of the backpacks have more upgrades?
- What are the contents of the internal backpacks? Does the main backpack contain anything besides the other backpacks?
- Can you provide the crash log? (The wall of text that shows when Minecraft crashes)

**Comment by gr8pefish** [comment]
@Killaheala With no more information I will be forced to close this issue soon.
