### ISSUE TITLE
NoClassDefFoundError crash when JEI is not installed

### ISSUE THREAD

**Issue by Hazerd** [gr8pefish/IronBackpacks#102]
#### Issue Description:
In a new instance of Minecraft 1.10.2 with only IronBackpacks installed, opening any inventory and right-clicking a slot will cause the game to crash.
`java.lang.NoClassDefFoundError: mezz/jei/api/IGuiHelper`
`at gr8pefish.ironbackpacks.client.ClientEventHandler.onGuiMouse(ClientEventHandler.java:55)`

#### Affected Versions (Do *not* use "latest"):
- IronBackpacks: 2.2.13
- Minecraft: 1.10.2
- Forge: 12.18.2.2125

**Comment by gr8pefish** [comment]
Yeah, it's listed as a hard dependency currently, I should (and will) alter that.
