### ISSUE TITLE
[2.2.14] Change in default MC pickup sound

### ISSUE THREAD

**Issue by MrGraphic** [gr8pefish/IronBackpacks#103]
Issue Description:
Latest changes in IronBackpacks affects default pickup sound. Sounds less "soft", louder and is strongly noticeable at multiple pickups.

Affected Versions:
- IronBackpacks: 2.2.14
- Forge: .2125

**Comment by gr8pefish** [comment]
Thanks for the report!

Fixed in the latest version [2.2.15] which is up on CurseForge now.

**Comment by MrGraphic** [comment]
Great, thanks!
