### ISSUE TITLE
Duping Bug

### ISSUE THREAD

**Issue by DTM450** [gr8pefish/IronBackpacks#104]
#### Issue Description:
Found duping bug with the filters of a backpack. I was using multiple filters not sure if it will affect the replication of the bug.

I should mention I was using Direwolf20's new 1.10 modpack

#### What happens:
double clicking an item that is in a filter when in shift rightclick of the backpack

#### What you expected to happen:
nothing

#### Steps to reproduce (important):

1. shift right click on back pack with a filter upgrade
2. place item in filter slot
3. double click item in inventory that is in filter slot

link to a short vid of the bug https://youtu.be/k5axE2UCBHU
____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.13
- Minecraft: 1.10.2
- Forge: 12.18.2.2124

**Comment by gr8pefish** [comment]
Thanks for the bug report! (And the helpful video)

New build should be up shortly with the fix.
