### ISSUE TITLE
Feature Request: Pass-through upgrade

### ISSUE THREAD

**Issue by DTM450** [gr8pefish/IronBackpacks#105]
Hey I thought of a neat little feature, a pass-through upgrade that allows items to be sorted to other nested backpacks but still needs filter upgrades on the nested packs to correctly sort them.

I suppose a pull-through that allows the restock upgrade access to nested packs would be nice too.

Or would this be too op

**Comment by Hazerd** [comment]
The Depth Upgrade does exactly this. Applying it to a Nesting backpack will allow all nested backpacks to retain the effects of their upgrades.

**Comment by DTM450** [comment]
:O I can't believe I missed it
