### ISSUE TITLE
Restocking Request

### ISSUE THREAD

**Issue by Mattabase** [gr8pefish/IronBackpacks#108]
This is a Feature Request 

While watching Direwolf20s latest Let's Play Episode I noticed the restocking upgrade does not working the Builder Wand from "Better Builders Wands" I assume that is the case for most wands of the same nature. 

If it is at all possible it would be great for it to work with those wands.

**Comment by gr8pefish** [comment]
[Almost done](https://streamable.com/czx8), just have to test it a bit more. I'm going to put some other minor things in the next version as well, so expect a release sometime late this week.
