### ISSUE TITLE
Another Disappearance Bug

### ISSUE THREAD

**Issue by srs-bsns** [gr8pefish/IronBackpacks#11]
I know you took v1.1.2 down already to fix bugs, but I thought I'd report this issue just to make sure you know of it.

An equiped backpack will disappear upon death.
-It will not drop with the rest of your inventory.
-It will not be put into an OpenBlocks grave.
-Even if /gamerule keepInventory is set to true, if will still disappear.

Regards,
~~Modding is srs bsns.~~

**Comment by gr8pefish** [comment]
Thanks, this is a good catch. I will leave this issue up until I have fixed it to make sure it doesn't get overlooked.

**Comment by gr8pefish** [comment]
Should be fixed in upcoming release
