### ISSUE TITLE
Duplication Issue

### ISSUE THREAD

**Issue by Gelles** [gr8pefish/IronBackpacks#110]
#### Issue Description:
Item Duplication on block placement with current recommended Forge (.2099) and Iron Backpacks. 

#### What happens:
Placing a block leaves a "extra copy" in the player's inventory that can also be placed infinitely. Reloading causes the item to reappear. It looks like the block is being placed, but not subtracted from the player's inventory.

#### What you expected to happen:

Place a block, subtract from inventory.

#### Steps to reproduce (important):

1. Put any placeable block down.
2. Right-click any empty space to place another block down, even if your hotbar shows empty.
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.17
- Minecraft: 1.10.2
- Forge: 12.18.2.2099

Pastebin of the block placement error:  http://pastebin.com/i7En6ZCN

**Comment by Gelles** [comment]
I did also notice that using Forge 12.18.2.2123 doesn't have this problem.

**Comment by gr8pefish** [comment]
Yup, update Forge to fix it. I thought I had the code to enforce this (greater than .2120), but apparently not. Will be strictly enforced in the next version to make sure others don't run into this issue.
