### ISSUE TITLE
Dupe bug with ender chest

### ISSUE THREAD

**Issue by thomasd1979** [gr8pefish/IronBackpacks#111]
#### Issue Description:
Backpacks opened from within an ender chest do not update their inventory when closed.

#### What happens:
All items added are deleted. All items removed are duped.

#### What you expected to happen:
not that.

#### Steps to reproduce (important):

1. grab any backpack (even basic with no upgrades)
2. place 10 of some item inside
3. place the backpack in an ender chest
4. open the backpack. Take the 10 items out
5. close the backpack
6. open the backpack. Take the 10 items out again
7. close the backpack
8. open the backpack. Note the 10 items still there. 
9. Place some other item in the backpack.
10. close the backpack.
11. open the backpack. Note the added item is gone.
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.17
- Minecraft: 1.10.2
- Forge: 12.18.2.2124

**Comment by TehNut** [comment]
Which Ender Chest? The vanilla one?

**Comment by Hazerd** [comment]
This appears to be happening when the backpack is opened via right-click from inside ANY inventory except for another backpack (with the nesting upgrade)
Seems to be the exact opposite behavior from #85
Also: I tested in Forge 12.18.2.2171 and IB 2.2.18 (the "latest" as of posting), it still happens.

**Comment by gr8pefish** [comment]
So I patched it with another bandaid style fix, this error will need to wait for larger scale internal changes to be implemented by myself be fully stable so I basically disabled it for all but backpacks -> other backpacks and normal 'e' inventory -> other backpacks (the 2 most common uses cases).
