### ISSUE TITLE
Nether Portal Error

### ISSUE THREAD

**Issue by katur239** [gr8pefish/IronBackpacks#112]
ERROR LOG: http://pastebin.com/ar8ZGBct

>java.lang.NullPointerException at >gr8pefish.ironbackpacks.util.helpers.IronBackpacksHelper.areItemsEqualForStacking(IronBackpacksHelper.java:346) ~[IronBackpacksHelper.class:1.10.2-2.2.18] at >gr8pefish.ironbackpacks.events.ForgeEventHandler.onBlockPlacedEvent(ForgeEventHandler.java:234) ~[ForgeEventHandler.class:1.10.2-2.2.18]

#### What happens:

Cannot create Nether Portal with Flint and Steel. Just creates a fire. Portal works on 2.2.17

#### What you expected to happen:

Nether Portal to open.

#### Steps to reproduce (important):

1. place obsidian in portal shape
2. activate flint and steel on block
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 2.2.18
- Minecraft: 1.10.2
- Forge: 2166

**Comment by gr8pefish** [comment]
Update Forge to 2120 or above, that should fix it. Did it not spam an error when using Iron Backpacks 2.2.18 that your forge wasn't the correct one?

**Comment by katur239** [comment]
It did not. I'll try that now.

**Comment by katur239** [comment]
Wait. I am already on 2166 which is above 2120.

**Comment by gr8pefish** [comment]
Oh wow, sorry I didn't read right, I thought that was 2016. I'll check it out.

**Comment by katur239** [comment]
Also I just updated Forge to 2171 and still errors.

**Comment by gr8pefish** [comment]
Sorry, missed some null checks. Should be good now, I'll push out a fix once I get something figured out for #111.
