### ISSUE TITLE
Block Placement

### ISSUE THREAD

**Issue by Ramiles45** [gr8pefish/IronBackpacks#114]
This is my own created Pack of 64 mods. 

#### What happens:

With nothing in my inventory, I can right click and place cobble. 
When I break a break I will either get double or more or any block.

#### What you expected to happen:

This to be fixed

#### Steps to reproduce (important):

1. Removed all mods except Iron Backpacks
2. Tested in a Creative world
3. Tried with the mod installed and uninstalled
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.17
- Minecraft: 1.10.2.
- Forge: 12.18.2.2017

**Comment by gr8pefish** [comment]
Update your forge and iron backpacks versions.
