### ISSUE TITLE
Tinker's Furnace voiding items with quick deposit upgrade

### ISSUE THREAD

**Issue by ghost** [gr8pefish/IronBackpacks#115]
#### Issue Description:
When I go to quick deposit items into the Tinker's Furnace, the items are voided instead of transferred. I will test the Smeltery later tonight.

#### Steps to reproduce (important):

1. Have backpack with the mining upgrade and the quick transfer upgrade with items in it
2. Place backpack into hand
3. Aim at the Tinker's Furnace controller and Shift-Right click
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.13
- Minecraft: 1.10
- Forge: 12.18.2.2124

**Comment by ghost** [comment]
When I Shift-Right click into the Tinker's Smeltery 2 different things happen depending on what items are in the bag. These also apply to the Furnace after some testing

If there are different types of items in each slot, the items will transfer successfully. This also applies to transferring items into the Furnace. 

If you have the multiple stacks of the same item in multiple slots, all but one stack will be voided in the Smeltery. In the Furnace, all the stacks are voided. I initially transferred a backpack full of oak wood. When I transferred Oak and Birch, the transfer was successful. In the smeltery I transferred multiple cobble, each in a different slot, and all but one was voided.

**Comment by gr8pefish** [comment]
Thanks for the bug report!

I'm super busy with finals, but I'll look into it as soon as I can.
