### ISSUE TITLE
Tomb Many Graves issue with backpack restoration when inventory is full

### ISSUE THREAD

**Issue by Xuerian** [gr8pefish/IronBackpacks#118]
#### Issue Description:
Backpack not stored in grave or restored

Also reported there: https://github.com/M4thG33k/TombManyGraves/issues/33

#### What happens:
When player's inventory, armor, and offhand are full and a backpack is equipped, it is not restored (at least, restored properly?)

Here's a snap of a player's data file and the ForgeCaps section, after picking up graves and not getting backpacks, if it helps: http://i.imgur.com/R3aYuIV.png

#### What you expected to happen:
Backpack to be re-equipped or dropped on activating the grave

#### Steps to reproduce (important):

1. Equip backpack
2. Fill inventory, armor, and offhand
3. Die
4. Activate Tomb Many Graves gravestone

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.17
- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- TombManyGraves: 1.10.2-2.1.13

**Comment by gr8pefish** [comment]
Thanks for the bug report!

I believe this is on TombManyGraves' side, as I simply drop the backpack onto the ground on death if the inventory is full. That being said, I'll look into it more to make certain, and if I need to make a PR to TombManyGraves to fix this then I might do just that.

**Comment by gr8pefish** [comment]
Confirmed to be on TombManyGraves' end (see issue linked above). Leaving this issue up until that one is closed to make sure the issue gets addressed.
