### ISSUE TITLE
Error instantiating the gui factory for mod ironbackpacks

### ISSUE THREAD

**Issue by RAnders00** [gr8pefish/IronBackpacks#12]
http://pastie.org/private/9jjjvnqh2oqhvd2kqfe9q

This is spit out to the log right after the Sound engine started (so a short moment before the title screen appears)

The game does not crash.

**Comment by gr8pefish** [comment]
Ah yes, that is just a result of me not initializing the in-game config gui. I plan on completing that, but in the meantime that error message shouldn't be indicative of any problems.
