### ISSUE TITLE
Cannot sneak-place on blocks with UI when a backpack is equiped

### ISSUE THREAD

**Issue by setycz** [gr8pefish/IronBackpacks#121]
#### Issue Description:
I cannot sneak-place any block onto any machine with UI when my iron backpack is equipped on my back.

#### What happens:
The block simply disappears, afterwards if I right click anywhere the block suddenly appears. Please see [the video](https://www.dropbox.com/s/9vvhdomf74kdty3/javaw%202016-12-10%2015-23-21-29.avi?dl=0) .

#### What you expected to happen:
The block is placed where I put it even if my backpack is equipped.

#### Steps to reproduce (important):

1. equip an iron backpack
2. sneak and try to place a vanilla hopper (any block) onto a vanilla chest (any block with UI)

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: IronBackpacks-1.10.2-2.2.19
- Minecraft: 1.10.2
- Forge: 12.18.2.2171
- Modpack: FTBPresentsDirewolf20110-1.1.3-1.10.2 (https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-10/files/2353000)

**Comment by gr8pefish** [comment]
Thanks for the bug report!

Does the equipped backpack have a quick deposit upgrade on it?

**Comment by setycz** [comment]
Yes, it's Storage Emphasis with:
* Mining Filter Upgrade
* Quick Deposit Upgrade
* Void Filter Upgrade
installed.

**Comment by gr8pefish** [comment]
Alright, I'll look into it! I'm busy with finals coming up in the next couple days, but I'll look at it as soon as I am reasonably able to.
