### ISSUE TITLE
Open Backpack hotkey won't stay configured

### ISSUE THREAD

**Issue by M4thG33k** [gr8pefish/IronBackpacks#128]
#### Issue Description:
Open Backpack hotkey won't stay configured. (I apologize in advance if this isn't due to your mod.)

#### What happens:
I've reset the "Open Backpack" hotkey several times (to apostrophe, if that matters) and it resets back to "C" every time I reload the world.

#### What you expected to happen:
The keybind to  persist.

#### Steps to reproduce (important):

1.  Change keybinding for Iron Backpack's "Open Backpack" button to apostrophe.
2.  Restart the game.
3.  Notice keybind reset.

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.26
- Minecraft: 1.10.2
- Forge: 1.10.2-12.8.2.2105

**Comment by gr8pefish** [comment]
Hmm, seems to work for me on first inspection.

Is this happening in your dev. environment, or in a normal world? Could you try replicating with no other mods than Iron Backpacks?

P.S. Did my change to fix to onDeathPRIORITY=NORMAL fix your trouble, or at least lead to more progress?

**Comment by M4thG33k** [comment]
It's currently happening in the dev world. The other hotkey works just fine, of course...

I will test it without other mods in a bit.

I'm just flushing out the Death Inventory List when one of your backpacks is in the grave, so yes the priority change is definitely helping.

**Comment by TehNut** [comment]
We had an issue like this in Blood Magic and it was caused by us registering our keybinds way too late. When do you register yours?

**Comment by gr8pefish** [comment]
Pre-init. [Here's](https://github.com/gr8pefish/IronBackpacks/blob/5287b38725546b3e3b2272e0eb337ac26426954c/src/main/java/gr8pefish/ironbackpacks/client/KeyHandler.java#L14-L14) the keybinding code exactly, registered in the client proxy during pre-init [here](https://github.com/gr8pefish/IronBackpacks/blob/b48f314a36378e396c39775aa2d66a970ce26319/src/main/java/gr8pefish/ironbackpacks/proxies/ClientProxy.java#L25-L25).

**Comment by gr8pefish** [comment]
@M4thG33k have you tried duplicating/discovering the cause of this issue since we last spoke?

**Comment by M4thG33k** [comment]
I haven't been able to reproduce it in my custom modpack, so maybe it was just a dev environment issue. Feel free to close this.

**Comment by gr8pefish** [comment]
Alright, thanks for the response.
