### ISSUE TITLE
Mod Specific Filter Upgrade picking up all items.

### ISSUE THREAD

**Issue by capyman5006** [gr8pefish/IronBackpacks#13]
The mod specific Item Filter is picking up all items. I have tried it with 4 different mods, Botania, Thaumcraft, Buildcraft, and railcraft. Once I set the filter the bag collects every item I pickup. The only way I found to stop it from picking up every item is by removing the filter item completely. First bug report so if there is anything else you need please let me know.

**Comment by gr8pefish** [comment]
Yup, it was a hacky implementation of that filter, I fixed how it is handled internally and now it works just fine! Will be in the next update.
