### ISSUE TITLE
Extra Utilities Builders Wand Restocking

### ISSUE THREAD

**Issue by Hazerd** [gr8pefish/IronBackpacks#130]
#### Issue Description:
Integration has been added for some Builders Wands in the past, however the wand from Extra Utilities has an odd effect where you lose blocks very quickly.
I've made [a video](https://youtu.be/v0NTia1mf7Q) showing this off in an instance with only IronBackpacks, Extra Utilities, and JEI.

#### What happens:
Blocks are removed from your inventory (not restocked), and a number of blocks greater than those used are removed from the backpack and voided.

#### What you expected to happen:
Only the amount of blocks placed should be removed from the backpack to restock those used.

#### Steps to reproduce (important):

1. Create a new backpack with a restocking upgrade, set to restock a material of your choice (in this case, stone).
2. Use a Builders Wand from Extra Utilities to place stone next to other stone.
3. Look in the backpack and notice you're losing much more stone than you are actually getting.

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 2.2.20
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by gr8pefish** [comment]
Thanks for the bug report!

I'll check it out tomorrow. If only all builders wands just acted the same way :P

**Comment by gr8pefish** [comment]
As shown in the commit, I just disabled compat to fix this for now. I might get around to implementing something custom for it later (I know *how* to do it), but it's not a high priority for me, as all the other builders' wands (e.g. Better Builders Wands, Too Many Wands, Botania) work fine.
