### ISSUE TITLE
Opening Backpack via Right click picks up half a stack of items in bag

### ISSUE THREAD

**Issue by exrok** [gr8pefish/IronBackpacks#132]
#### Issue Description:

Opening Backpack via Right click picks up half a stack of items in bag. I think it might be a conflict with inventory tweaks.

If you click really fast it does not occur. 

Possible easy fix maybe be able to set the key it uses to open a bag in a inventory to something else.
#### What happens:
Opening Backpack in another bag via Right click picks up half a stack of items in bag

#### What you expected to happen:
To only open it up the backpack in another bag and not have right click a stack in the inventory.

#### Steps to reproduce (important):

1. Have an Iron bag (Storage Eph.) filled with cobble in the second slot of a 
    diamond bag (upgrade Eph.) 
2. Right click the Iron bag from inside the diamond bag to open it
3. Observe the bug
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.20
- Minecraft: 1.10.2
- Forge:  12.18.3.2185

**Comment by gr8pefish** [comment]
Thanks for the bug report! I'm currently away from my computer, visiting family for Christmas, but I'll be sure to take a look at the issue when I return (just over a week from now).

**Comment by gr8pefish** [comment]
Alright, I think I fixed this, but I'm not 100% certain, so if you encounter it again please let me know (comment here and I'll reopen the issue). Thanks!

**Comment by gr8pefish** [comment]
My "fix" of this broke something else, so I'm reverting it and reopening this issue.

**Comment by gr8pefish** [comment]
I believe this was fixed a while ago, I just forgot to close this issue :P
