### ISSUE TITLE
Game crashes on mod update (1.10.2)

### ISSUE THREAD

**Issue by LordHellscream** [gr8pefish/IronBackpacks#137]
#### Issue Description:
Game crashes on launch, I was updating all the mods (haven't played for a while), then I noticed the game starting to crash on launch, so I took out all the mods and added them back one by one. Eventually the crash occurs when I added back this mod, I love the mod, it would really suck if I don't get this working. If this is not the cause, please give me a hint on what may be causing it! Thanks, and keep up the good work!

Log:
http://pastebin.com/73hcD3Bx

**Comment by gr8pefish** [comment]
What was the version you had before? And what version are you trying to update to?

It looks like you are trying to use the 1.8 version. Make sure you are using the right version of Iron Backpacks (1.10.2-2.2.21 at the time of this writing).

**Comment by LordHellscream** [comment]
it looks like it may have been a mistake from my end. Let me confirm this and get back to you.

**Comment by LordHellscream** [comment]
ok it looks like I accidentally downloaded the 1.8 version, and somehow the game didn't complain about it but attempted to load it anyway, that may be the cause of the crash, i downloaded the correct version and the crash stopped. Sorry to bother you, will close this now

**Comment by gr8pefish** [comment]
Haha no worries, glad you got it fixed.
