### ISSUE TITLE
JEI recipes are taller than the background, so they can overlap each other

### ISSUE THREAD

**Issue by mezz** [gr8pefish/IronBackpacks#138]
![2017-01-01_20 55 35](https://cloud.githubusercontent.com/assets/916092/21584760/ad39c5ea-d064-11e6-8938-389f26d353e6.png)

If you make the blank background taller so that all text is over the background, JEI will be able to lay it out without overlapping text.

**Comment by gr8pefish** [comment]
Perfect, will do. Thanks for the bug report!
