### ISSUE TITLE
x-mod issue: Mining filter item collection conflicts with Baubles Stuff magnet

### ISSUE THREAD

**Issue by xenoflot** [gr8pefish/IronBackpacks#139]
#### Issue Description:
I've added a Mining Filter to my gold backpack. If I have a Baubles Stuff Magnet Ring (Instantaneous) in the bauble slot, ore is deposited into my inventory, rather than into the backpack.

The non-instant version of the BS magnet ring doesn't cause this. Backpack works as expected.
The ActuallyAdditions magnet also cooperates.

I'm speculating that the instantaneous version of the BS magnet is placing the items directly into the inventory rather than using the itemPickup function

I'll crosspost this to the BS git but perhaps you might want to have a look to see if you can work around that.
____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.21
- Minecraft: 1.10.2
- Forge: 2185
- Baubles: 1.10.2-1.3.8
- BaublesStuff: 3.0.2

**Comment by gr8pefish** [comment]
Yeah, that's exactly what's happening, they just need to call onItemPickedUp, and the issue should be solved. I'll leave this issue up until then though.

**Comment by gr8pefish** [comment]
Just waiting on them still, closing this issue on my end.
