### ISSUE TITLE
So are you abandoning the mod? 

### ISSUE THREAD

**Issue by mindcloud69** [gr8pefish/IronBackpacks#14]
So are you abandoning the mod?

**Comment by gr8pefish** [comment]
I have been quite busy with other things going on in my life this summer and did not have the time nor inclination to work on the mod in that time, but I was going to resume working on it soon . However, I will be studying abroad and my old laptop cannot handle MC, so I doubt I will be able to work on it for the next ~3 months. I do expect that I will be able to come back to modding when I return to the country though. If it were a couple easy fixes I would have already done it, but as I have to rewrite some networking/custom GUI opening code (that I am far from an expert on) it will take some time.

**Comment by mindcloud69** [comment]
Thank you for the update.

**Comment by gr8pefish** [comment]
Update 2: I got MC to work on my laptop! I get like 10 fps, but that is enough for development work, even if testing is a bit rough xD I am quite busy with school (taking a Masters level course), and I want to travel around Europe quite a bit while I am here, but I can do _some_ dev work now at least.

**Comment by gr8pefish** [comment]
Just uploaded the new version to curseforge. Feel free to check it out!
