### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Hazerd** [gr8pefish/IronBackpacks#140]
[OpenEye Report](http://openeye.openmods.info/crashes/9e3393cf84f962b77bd2e9c92443cdab)
#### Issue Description:
After upgrading my backpack to Diamond and adding an Advanced Nesting Upgrade I made a new backpack (iron) and put it in the bottom-right slot (76) and tried to right-click that backpack.

~~After logging back in the problem was fixed. I don't really have a good explanation besides some ArrayList wasn't extended (or created) as large as it should've been.~~
Edit: Apparently not... Sometimes I can open the backpack properly, sometimes it crashes, I have no idea what I am doing differently when it does crash.
#### What happens:
IndexOutOfBoundsException, the OpenEye report has the stacktrace.

#### What you expected to happen:
The nested backpack should have been opened as normal.

#### Steps to reproduce (important):
(Might not work to reproduce, just what I had done)
1. Created new backpack, used it for a bit (equipped)
2. Upgraded to Iron, continued to use regularly (equipped)
3. Upgraded to Gold, then immediately to Diamond.
4. Added Advanced Nesting Upgrade.
5. Equipped and removed everything inside.
6. Created a new backpack, upgrading directly to iron.
7. Put the new backpack in the bottom-right slot.
8. Attempt to right-click to access the nested backpack.
____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 2.2.22
- Minecraft: 1.10.2
- Forge: 12.18.3.2202
- Other Conflicting Mods: Possibly MouseTweaks v2.6.4

**Comment by gr8pefish** [comment]
Thanks for the bug report, I'll check it out tomorrow.

**Comment by gr8pefish** [comment]
Sorry, tomorrow turned into much later, I'm in the middle of a super intense medical course that leaves no free time (and therefore no modding). I'll get to it when I can (likely next week sometime).

**Comment by Hazerd** [comment]
No problem, the issue did go away when I removed MouseTweaks, so it is an interaction between the two but the actual crash seems to be on IronBackpacks' side.

**Comment by hairlessOrphan** [comment]
I know I'm supposed to report modpack crashes to the modpack author, but I thought it would be helpful to report: getting the same crash in SkyFactory 3 Modpack, using exactly the same steps as Hazerdous (I mean *exactly*, including using the Iron backpack for a while, then upgrading to Gold and then immediately Diamond, and including putting the second Iron backpack in the bottom right slot. The ONLY difference between our apparently identical playstyles is I had a Mod Filter for Chance Cubes in the nested Iron backpack).

Also, like Hazerdous, removing Mouse Tweaks from the mod pack stopped the crash.

**Comment by gr8pefish** [comment]
Hi all. Sorry for the delay, life has been busy.

Can you try disabling Mouse Tweak's `Right Mouse Button Tweak` option, and see if that fixes the issue? Hopefully that would allow you to keep both mods in, but not crash.

**Comment by Hazerd** [comment]
I am playing on a different pack now and haven't run into this issue (MouseTweaks is still installed, same version)

I had, however, encountered #132 on this instance. Your suggestion to disable `RMB tweak` fixed that. (I hadn't enountered that issue in any other instance, I feel like these issues may be based on more than 1 mod interaction happening at a time)

**Comment by gr8pefish** [comment]
Yes, that's my guess as well. I assume that many mods subscribe to the `onRightClick` event and some do some interesting/non-other-mod-friendly things with it. I doubt it is on my end in this case, as I explicitly check for an Iron Backpack before doing anything special.

Glad to hear that the RMB disabling worked! I'll contact the Mouse Tweaks author to try and get this fixed. As for now, I'm going to close this issue, but if you come across anything else please feel free to make a new issue (or post here again and I'll reopen it). Thanks!

**Comment by gr8pefish** [comment]
Okay, I believe it is fixed completely with the latest version of Mouse Tweaks now!
