### ISSUE TITLE
1.7.10 Crash when shift-clicking anything

### ISSUE THREAD

**Issue by feryaz** [gr8pefish/IronBackpacks#141]
#### Issue Description:
I have a diamond bag with nested and depth upgrade with a gold bag with mining, damage bar and void upgrade in it. Whenever I shift-click anything besides a building block, like a bed or a machine, with my bag in the hand it crashes. The stacktrace only contains minecraft and ironbackpacks, I'm using FTB Infinity Evolved. While we are at it, any chances for the right-click to open function to be backported to 1.7.10? Really missing it after going back and it would solve this issue for me as well ;)

#### What happens:
Crash http://pastebin.com/SWPj5HJm

#### What you expected to happen:
No crash

#### Steps to reproduce (important):

1. Have bag in hand
2. Shift-click bed
3. Profit

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: IronBackpacks-1.7.10-1.2.20
- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- Other Conflicting Mods (may be irrelevant to your issue):
http://pastebin.com/SWPj5HJm

**Comment by gr8pefish** [comment]
So sorry, but I'm busy enough that I probably won't ever get around to this (realistically). I need to prioritize newer versions.
