### ISSUE TITLE
Incompatability with Draconic Evolution "blobs"

### ISSUE THREAD

**Issue by davelien** [gr8pefish/IronBackpacks#142]
#### Issue Description:
When using a Draconic Evolution tool which mines in a 3x3 or greater pattern "blobs" of aggregated blocks are dropped in order to reduce lag.  These "blobs" are not picked up by Iron Backpacks.  See https://github.com/brandon3055/Draconic-Evolution/issues/526#issuecomment-270541619 for a screenshot of the blobs.

I have opened an issue with the Draconic Evolution developer at https://github.com/brandon3055/Draconic-Evolution/issues/527

#### What happens:
The DE lag-reducing "blobs" are picked up into the player inventory.

#### What you expected to happen:
I would hope that Iron Backpacks could actually pick up the blocks mined by Draconic Evolution tools.

#### Steps to reproduce (important):
1.  Equip an Iron Backpack with mining upgrade and a filter properly configured
2.  Mine with a Draconic pickaxe set to 3x3 or larger
3.  Pick up mined blobs
4.  Mined materials/blocks appear in player inventory 
____
#### Affected Versions (Do *not* use "latest"):

Direwolf20 1.10 Modpack
- IronBackpacks: 1.10.2-2.2.22
- Minecraft: 1.10.2
- Forge: 
- Other Conflicting Mods (may be irrelevant to your issue): Draconic Evolution 1.10.2-2.0.6.157-universal

**Comment by gr8pefish** [comment]
I will look into it on my end, but my guess is that Brandon isn't calling onItemPickedUp for his blobs, and without that there is no way I can make it work.

**Comment by TehNut** [comment]
I just looked, he indeed does not fire `ItemPickupEvent0` (or `EntityItemPickupEvent`). This issue is on their side.
