### ISSUE TITLE
A small spelling mistake in the description of the compression upgrade

### ISSUE THREAD

**Issue by NerdMcBoon** [gr8pefish/IronBackpacks#143]
#### Issue Description:
The description of the compression upgrade says "The items in this inventory _of_ ghost items...", when it should probably say "The items in this inventory _are_ ghost items...".
Sadly I was dumb enough to forget to check the other descriptions as well. As this line was probably copied from other descriptions, the mistake may occur in them as well.

![ironbackpackstypo](https://cloud.githubusercontent.com/assets/16770970/21741606/cb46ee70-d4db-11e6-9536-1d6cc4b2474c.png)

#### What happens:
A typo.

#### What you expected to happen:
No typo.

#### Steps to reproduce (important):
1. Read the text.
2. Be amazed.

#### Affected Versions (Do *not* use "latest"):
- IronBackpacks: 1.10.2-2.2.22
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2202

**Comment by gr8pefish** [comment]
Thanks for the bug report, I'll fix this immediately.
