### ISSUE TITLE
"Let's carry everything" achievement says "Invalid statistic/achievement!" on mouseover

### ISSUE THREAD

**Issue by Ricket** [gr8pefish/IronBackpacks#144]
Mouseover the "Let's carry everything" achievement, it shows "Invalid statistic/achievement!" instead of a description.

![image](https://cloud.githubusercontent.com/assets/196978/21744674/6acff34a-d4e8-11e6-8d0d-97ec4aee71f4.png)

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks-1.10.2-2.2.21.jar
- Minecraft: 1.10.2
- Forge: 2185
- Direwolf20-1.10 pack version 1.3.2

**Comment by gr8pefish** [comment]
`Let's carry everything` isn't an achievement from my mod; Iron Backpacks has only The Basics, Ironing Things Out, Gilded Age, and Tier-y Eyed. I believe you need to report this to a different mod author.

**Comment by Ricket** [comment]
Ah, sorry I assumed based on the prior achievement. Looks like it's a Bagginses achievement. I guess he was testing the two different bag mods :)
