### ISSUE TITLE
Feature request: Add a setting to temporarily switch the void upgrade off

### ISSUE THREAD

**Issue by pfmoore** [gr8pefish/IronBackpacks#146]
It's very easy to remove items from the void upgrade filter, But I never remember to add them again after I've finished collecting what I need.  When I do get round to remembering, I have to go and find the items I want set to void. While this isn't exactly hard for things like cobble, it's a minor irritant, and for more complicated uses it might be awkward.

Would it be possible to add a "disable" checkbox to the void upgrade settings, that just switched it off temporarily? It would be a useful quality of life improvement for me.

**Comment by gabor7d2** [comment]
I don't know how complex it would be to do, but it would be cool if the upgrades you take off of the bags would remember their settings.

**Comment by gr8pefish** [comment]
> add them again [to the void filter]

Is it really that difficult? I don't want to sound condescending/rude/etc. but it seems very simple to put the item back, as if you remove it then you are nearly guaranteed to have said item in the first place. Could you give me an example of a 'more complicated use' so I can understand your viewpoint more?


> remember their settings

Would increase the data size of the backpacks internally substantially, so I'm going to avoid that if at all possible

**Comment by pfmoore** [comment]
> Is it really that difficult?

Not massively, to be honest. The main time it hits me is when I am doing some building work and I forget to put my mining pack away. I then end up with the pack on me, nowhere to put it down, and no way to switch it off, and so wondering why I have no "filler" cobblestone available. It's far from being crucial, mostly just a minor annoyance that I hit a lot. The "more complex" situations I had in mind were when I had a lot of items being voided, but just didn't want to clear them all out and set them back up again.

> Would increase the data size of the backpacks internally substantially

That's a good enough reason for me. Thanks for considering the idea, though.

**Comment by gr8pefish** [comment]
Okay, fair enough. If I add something it would be along the lines of a quick toggle to enable or disable any upgrade.

**Comment by gr8pefish** [comment]
I'm going to be reworking the void upgrade a bit in the 1.12 rewrite, and I'll address this issue then.
