### ISSUE TITLE
Fix Crash With Quick Deposit And Applied Energistics 2

### ISSUE THREAD

**Issue by DavidSwain** [gr8pefish/IronBackpacks#149]
#### Issue Description:
Game crash when using Quick deposit and AE2.

#### What happens:
This only seems to happen when using Precise QD into a e.g. Pattern Terminal. Using the normal QD deposits all the bags inside the original. Using PQD, Advanced Nesting, and Depth upgrades on the first bag with several bags inside (with normal items in e.g. cobble) crashes the system.

#### What you expected to happen:
I expected it to deposit the cobble in one of my bags (cobble was in the system) into the system, but leave all the bags in my original bag in there.

#### Steps to reproduce (important):

1. Make (diamond) bag
2. Add PQD, Nesting and Depth to bag. 
3. Make another (gold) bag.
4. Put item in the gold bag.
5. Create simple AE2 storage system (Some form of power, energy acceptor, controller, drive (with storage card installed), pattern terminal on cable.
6. Place x-item in the storage system and x-item in gold bag.
7. Shift click pattern terminal.
____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 
- Minecraft: 
- Forge: 
- Other Conflicting Mods (may be irrelevant to your issue):
I tried this on the mod Space Astronomy by MJRLegends. Therefore there could be a number of conflicting mods but I imagine it's just AE2 and IB. (loaded through Curse Launcher)

**Comment by gr8pefish** [comment]
What version of Iron Backpacks was this for? 1.10 I'm guessing?

**Comment by gr8pefish** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Quick Deposit + AE2 Crash](https://trello.com/c/Dyfe2XIW/37-fix-quick-deposit-ae2-crash)

**Comment by gr8pefish** [comment]
Probably the same cause as #148, and no response, so closing this.
