### ISSUE TITLE
Bagpack lost upon death with Gravestones mod

### ISSUE THREAD

**Issue by xorinzor** [gr8pefish/IronBackpacks#151]
We are running the Direwolf20 1.10 modpack (version 1.6.1) and while playing figured out that the **equipped** bagpack doesn't go into the grave (nor gets dropped as an item, both cases with an empty player-inventory).

It simply disappears. This seemingly was adressed in #40 already, but somehow it managed to come back.

The IronBackpacks mod version is: 1.10.2-2.2.22
The gravestones mod version is: 1.5.12

**Comment by gr8pefish** [comment]
I think this should work. I tested it with all the combinations I could think of (equipped with eternityUpgrade/keepInventoryTrue/neither), and they all seemed to work just fine as-is.

I'm using IB v2.2.22 and [this gravestones mod](https://minecraft.curseforge.com/projects/gravestone-mod) v.1.4.9. Try updating and testing again. If you still get that issue please repost here with more detail and I'll reopen the issue and try and fix it. 

Thanks!
