### ISSUE TITLE
BackPacks-Filters causing EXTREME Lag

### ISSUE THREAD

**Issue by OldDogy** [gr8pefish/IronBackpacks#154]
Modpack: All The Mods - Expert

#### Issue Description: 
Backpacks make EXTREME lag.
((Everything is mostly explained underneath, But i want to make it clear that this issue is CRITICAL when the inventory is full, and items on the ground are not on the backpack filter, Still the backpacks are causing issues even when your whole inventory is empty ! I'll assume the way you test if the item should go in to the bag is not good.))

#### What happens:
Extreme Lag, Both single-player and Server continuously drop in TPS until timeout.
The backpack is trying to pickup items from the ground, I assume constantly running the code trying to pickup an item that's not on the filter and deciding it shouldn't pick it up only to test it again and again ?

#### What you expected to happen:
Nothing. The backpack is not supposed to check if it can pick up the item over and over again until the end of the world.

#### Steps to reproduce (important):

1. Make any backpack, and put any filter on it, so that the backpack would pull items automatically in.
2. Fill up your inventory (example with cobble+one slot with the backpack)
3. Drop an item that u can't pick up (and isn't on your backpack filter)
4. Stand on top of the item that is on the ground and watch the game DIE

____

Now imagine a few nested bags that all have different filters ... 

#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: IronBackpacks-1.10.2-2.2.23
- Minecraft: 1.10.2
- Forge: 12.18.3.2239
- Other Conflicting Mods (may be irrelevant to your issue): / none

**Comment by gr8pefish** [comment]
Can you clarify on the "steps to reproduce" please"?

1) Do you put anything _in_ the filter?
2) The player's inventory, the backpack, both? Where is that "1 slot"?

Here's what I'm testing with right now, to no issue:
http://i.imgur.com/ObMndh7.png
http://i.imgur.com/5e7Nyev.png

**Comment by OldDogy** [comment]
## **I am sincerely Sorry, Please close this issue I have done additional testing with only your mod active, and can not replicate it.** 
_{In-depth:
This is happening on All The Mods-Expert 1.0.27 Server

I have a diamonds storage backpack(nesting & depth upgrade) with , iron storage backpack (Basic Filter & 3x3 compressing upgrade)(( In the filter i have cobble and dirt) and in the compression i have both cobble & dirt ->double compressed cobble &dirt [this is from Extra Utilities 2] all the way up to the 4th compression level)
There is no need to Fill up all backpack spaces, simply filling up my inventory and standing above a dropped item that i can't pickup kills the server. }_

-----
## Doing further testing I came to the conclusion that something is wrong with there server machine it self.
## Since i Can not reproduce it on a local test server I made. 
If we come across any new discovery i'll send out an update. 
Once again, Sorry for the inconvenience!

**Comment by OldDogy** [comment]
I have put more stress on the bag, filled it up with half a stack of few compressed cobble and dirt tiers from extra utilities. And it started crashing. Can't provide more info then that 😞

**Comment by AmperChild** [comment]
I have the same problem with the compression and a filter (in my case mining filter). The problem starts when I use a magnet (any kind). I assume the magnet trys to insert the items into my inventory but the bag still packing MULTIPLE things.
