### ISSUE TITLE
Crash in Achievement Screen

### ISSUE THREAD

**Issue by tfox83** [gr8pefish/IronBackpacks#155]
Submitted to me (FTB Beyond pack dev): https://forum.feed-the-beast.com/threads/iron-backpacks-achievements-crash.220654/

#### Issue Description:
When panning to the upper left corner of the Iron Backpacks achievements screen, the game crashes. 

#### What happens:
Game Crash: http://paste.feed-the-beast.com/view/9a4ac3f7

#### Affected Versions (Do *not* use "latest"):
- IronBackpacks: 2.2.23
- Minecraft: 1.10.2
- Forge: 2254
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by gr8pefish** [comment]
Thanks for the bug report! I'm swamped today, but I'll try and fix it tomorrow.

**Comment by gr8pefish** [comment]
Looks like it is a [Forge bug](https://github.com/MinecraftForge/MinecraftForge/issues/3293) and happens with all mods.
