### ISSUE TITLE
[1.7.10] Feature Request/Bug? Restocking Upgrade only triggers when an item is picked up.

### ISSUE THREAD

**Issue by Exorno** [gr8pefish/IronBackpacks#156]
Restocking says it will try to keep a stack of the item in your inventory, but only triggers when picking items up.  It would make more sense to trigger when placing items, because that's when you would need restocking.

I suggest it attempts to restock when stack size reaches 32 or below.

**Comment by gr8pefish** [comment]
Sorry, not adding features to 1.7 anymore. While you are 100% correct, and I would love to add this sort of stuff, realistically I know I won't be able to get to it (just too damn busy unfortunately). Try the 1.10 version; it addresses this issue (among others).
