### ISSUE TITLE
Backpack rendered on player despite no backpack being worn

### ISSUE THREAD

**Issue by Partonetrain** [gr8pefish/IronBackpacks#158]
Hi, figured I'd 'officially' report the bug.
#### Issue Description:

Backpacks are rendered on players despite not having a backpack equipped

#### What happens:

What appears to be a diamond backpack is rendered on my player, but I don't have one equipped. 

#### What you expected to happen:

No backpack renders.

#### Steps to reproduce (important):

1. Go into third person
2. Look at back
...

____
#### Affected Versions (Do *not* use "latest"):

- Modpack is FTB Beyond 1.2.0
- IronBackpacks: 2.2.23
- Minecraft: 1.10.2
- Forge: 12.18.3.2254
- Other Conflicting Mods (may be irrelevant to your issue): Possibly none, possibly one of the mods in the modpack

I don't have the time to test an instance with only Iron Backpacks at the moment, but I will get back to you if/when I do.

**Comment by Hazerd** [comment]
Backpacks don't normally render just by being in your inventory, they​ render when worn. The default keybind to equip/unequip is `v`, to open one on your back the default is `c`

**Comment by gr8pefish** [comment]
Some clarification details:

* Were you by someone else who did have an equipped backpack on?
* Did you recently put on/take off a backpack?
    * Note the color of the pack to try to determine the above; I would like to know _which_ backpack is rendering on the player that shouldn't be appearing.

Thanks

**Comment by Partonetrain** [comment]
No to both questions. As far as I know no one in the server has used a backpack from this mod.

Sorry, that probably doesn't help much, but that's what happened.
