### ISSUE TITLE
IronBackpacks corrupts world

### ISSUE THREAD

**Issue by Sir-Will** [gr8pefish/IronBackpacks#16]
hey,

I had to remove the IronBackpacks mod as it corrupted the world.
After a while all players got kicked out of the server and after this it was no longer possible to connect again.
Restarting the server didn't fixed it. I did a rollback but it happened again after an hour and after removing the mod the issue was gone.

How you can see in this log that the server handles your itemPickupEvent and all players get kicked. After that a player tries to join but gets disconnected.
http://pastebin.com/uUnMAp6Y

**Comment by Sir-Will** [comment]
Weird. It is not the backpacks mod which caused the connection issues. Not sure why it worked after removing the mod the first time. But the issue with the crafting upgrade and global kick still counts.

**Comment by gr8pefish** [comment]
My guess is it is a recipe conflict, and when my backpack tries to pick up an item to craft it runs into an issue there, hence kicking the player. Check what was in the player's crafting slots (i.e. what he was trying to craft) and then maybe minetweak that or make sure the recipe is okay. If you still have issues let me know.
