### ISSUE TITLE
Player Losing Backpacks when dieing.

### ISSUE THREAD

**Issue by Speiger** [gr8pefish/IronBackpacks#161]
Note: Delete the following 2 lines when you submit the issue. 
* If this bug occurs in a modpack, please try first reporting it to the modpack author. Barring that, please narrow down exactly what other mod(s) are responsible for the issue. 
* If this is a feature request, this template does not apply to you. Just delete everything and write what you need.

#### Issue Description:
When a player dies he loses his backpack completely. Its not in the drops either.

#### What happens:
The Player Died and the bag wasnt in the drops. Happens frequently.

#### What you expected to happen:
To find the Backpack into the drops.

#### Steps to reproduce (important):

1. Equip a backpack/have it in the inventory
2. Die,

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks:  1.10.2-2.2.23
- Minecraft: MC 1.10.2
- Forge:  2254
- Other Conflicting Mods (may be irrelevant to your issue): 
https://www.feed-the-beast.com/projects/ftb-beyond There are all mods.

**Comment by gr8pefish** [comment]
Okay Speiger, you know the drill. More info is needed:

- Is it only with an equipped backpack or backpack item in the inventory, or does it happen with both?
- Is the inventory full when this happens?
- Does the player have `gamerule keepInventory true` on when this happens? 
- Does it appear to be a conflict with a gravestone mod?

Thanks

**Comment by Speiger** [comment]
ok no problem:
- Both.
- No
- is set to false.
- Is disabled

Do you need more?

**Comment by gr8pefish** [comment]
Huh, strange. If none of those conditions are true then it should've popped up here much more frequently.

Do you have a way of replicating the error (does it happen as simply as described above, with no extra steps)?

**Comment by Speiger** [comment]
What i think is that you use the onDeathEvent.
I had issues with that in my own mod. SpmodAPI. (Weird name but deal with it).
And when i switcht over to PlayerDropsEvent and set the Player.captureDrops to true while my logic ran.
That seems to have it fixed on my side.
Because they get then spawned properly.

**Comment by Speiger** [comment]
I honestly dont know why that fixed it in my mod but its a close situation.
My Situation:
You got a special drop when you killed yourself with 50 lvls of XP and close to midnight.
I had always issues until i switcht to that event.

**Comment by gr8pefish** [comment]
Hmm, I might try that, but wouldn't it break compatibility with some graves mods? As they check for death and not necessarily player drops? Or did you not find that to be the case?

But thanks for the suggestion; I might try implementing it that way.

**Comment by Speiger** [comment]
Nope because Gravestone spawns a block and waits until all drops spawned and then collects the items that try to spawn at that area of effect or are already spawned in that area.
To be extra sure put it on high priority. I doubt that they put themselves on high since they want to catch everything.

**Comment by Speiger** [comment]
@gr8pefish dont forget to set capture drops to false after you logic is over else you fuck even more stuff up.
