### ISSUE TITLE
Nested backpacks don't make use of filters

### ISSUE THREAD

**Issue by Ferrousofel** [gr8pefish/IronBackpacks#17]
When nesting backpacks, a nested backpack does not appear to pull in items. 

My specific example is a general use backpack with a backpack condensing cobble, redstone, etc. while mining.

Gold backpack(with advanced filter, cobblestone pulling in) containing another gold backpack(crafting upgrade with cobblestone, basic filter with cobblestone).

The above case only seems to pull cobblestone into the general use backpack, but nothing I've done has gotten the cobblestone to be pulled into the nested backpack. Is there a trick to getting this to work, or is it even not an intended usage?

**Comment by gr8pefish** [comment]
Yes, this is not an intended behaviour (yet). Should come with the next release, which will not occur until after new years, as I am studying abroad this semester and cannot work on it.
