### ISSUE TITLE
Mining upgrade does not pick up items in specific cirumstances

### ISSUE THREAD

**Issue by BSFishy** [gr8pefish/IronBackpacks#170]
#### Issue Description:
If you have a backpack with the mining upgrade on it, it will not automatically pick up items if your inventory is full. If you make room, though you can pick up the item, and it goes directly into your backpack.

#### What happens:
The items do not go into the backpack.

#### What you expected to happen:
The items to automatically go into the backpack.

#### Steps to reproduce:

1. Create a backpack with the mining upgrade
2. Fill your inventory with items
3. Try to pick up an item that is picked up by the mining upgrade
4. Be sad

____
#### Affected Versions:

- IronBackpacks: 2.2.25
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

**Comment by gr8pefish** [comment]
Seems to work just fine for me: https://streamable.com/sm1mi

Try updating and report back.

**Comment by gr8pefish** [comment]
I haven't heard back, so I'm closing this issue.

If you run into it again and have more info, feel free to reopen this issue and post more details.
