### ISSUE TITLE
1.11.2 Question.

### ISSUE THREAD

**Issue by MrSapient** [gr8pefish/IronBackpacks#173]
I'm in the process of updating my modpack to 1.11.2 and this is one of only 4 mods not updated to 1.11.2.. I'm in no way asking you to rush or expecting you to.. I'm only asking if you do have plans to update or if you are taking a break/moved on from modding. 

Thanks

**Comment by gr8pefish** [comment]
Yup, working on it. Check out the 1.11 branch if you want to see the details. Shooting for basic release early July.
