### ISSUE TITLE
Possable new tier

### ISSUE THREAD

**Issue by KhaosKrew-Kirito** [gr8pefish/IronBackpacks#174]
Would it be possable to have a new tier of the backpacks like star tier that requires 4 blocks of nether stars to craft in up grading the diamond one and has double the space of the diamond or just holds more

**Comment by gr8pefish** [comment]
Yeah, but it will be in 1.12+. I'm explicitly building the API so that it should be simple to add new tiers of backpacks, be it with my mod (internally, or possibly with even some config/json user directed tomfoolery) or, more likely, an addon mod.
