### ISSUE TITLE
SF3 restock not working with sieves

### ISSUE THREAD

**Issue by Runisco** [gr8pefish/IronBackpacks#175]
#### Issue Description:
When using an Iron backpack with restock upgrade configured to gravel, it will not restock the gravel when used on a sieve, or a grid of sieves.

#### What happens:
The item configured to be restocked will just deplete. Yet when a single of the item is placed on the ground, the restock triggers again, still not working on sieves

#### What you expected to happen:
The restock upgrade should restock the gravel used by the sieves

#### Steps to reproduce (important):

1.  Make an iron backpack with restock option
2. 5x5 grid of sieves with diamond mesh
3. Configure the restock upgrade to restock gravel, then right click on sieve to deplete. It does not restock
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 2.2.27
- Minecraft: 1.10.2
- Ex Nihilo Adscensio: 0.1.20
- Forge: 
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by gr8pefish** [comment]
Sorry for the delay, I was on vacation. Will be on a new version on CF real soon, but I don't know if Darkosto will update the main pack with it (messaged him but awaiting a reply).
