### ISSUE TITLE
[Bug/Glitch] Duplication of backpack contents

### ISSUE THREAD

**Issue by Mustang007m** [gr8pefish/IronBackpacks#176]
#### Steps to reproduce (important):

1. Put items in backpack.
2.  Throw and open backpack at the same time. Timing is a bit tricky but not hard once you find the spot.
3.  Collect the items from the phantom inventory.
4. Pick up the backpack from the ground and collect the items in the backpack.
5. Profit? (Seriously you end up with double of all items in the backpack.)
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.27
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2316
- Other Conflicting Mods (may be irrelevant to your issue): Not relevant tested with just the above.

I am a server owner and this is a rampant problem on my server that I am trying to fix. I tested outside of my modpack to make sure it would still happen and it does. Even if a fix cannot be implemented a workaround or way to patch it would be welcome. Thank you for your time and attention. Love the mod. I have a video if needed.

**Comment by TehNut** [comment]
Does this occur in both SP and MP?

**Comment by Mustang007m** [comment]
Yes. It is possible in both.

**Comment by gr8pefish** [comment]
Can you provide the video please? I can't reproduce the issue on my end.

Just clarifying, you did test with _only_ Iron Backpacks, correct?

**Comment by Mustang007m** [comment]
Of course. Yes, just forge and Iron Backpacks.

**Comment by Mustang007m** [comment]
Doing some testing on a control environment get back to you asap

**Comment by Mustang007m** [comment]
If you add nothing but JEI and ironbackpacks to your test environment you should be able to reproduce, I was mistaken when I said that I tested with only Ironbackpacks I was also using JEI. Which seems to be a catalyst for this bug.

**Comment by Mustang007m** [comment]
https://www.dropbox.com/s/resj3n42cdrwktt/DupeIronBackpacks.mp4?dl=0

**Comment by MJRLegends** [comment]
I have confirm im getting this issue too https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/47

**Comment by gr8pefish** [comment]
Sorry for the delay, you caught me right as I went away on vacation. I'll push out a new build with this fix (and others) tomorrow.

**Comment by MJRLegends** [comment]
Thank you :P

**Comment by gr8pefish** [comment]
No problem. Build should be out now as well, I lied with my time estimation xD
