### ISSUE TITLE
[1.10.2] Client Crash 

### ISSUE THREAD

**Issue by yepidoodles** [gr8pefish/IronBackpacks#178]
#### What happens:

One of my players reported this issue/ crash on one of my servers, this is in her own words as to what happened:

```
i made a leather backpack from iron back packs and when i opened it then hit shift it crashed me then i logged back on and opened in and his esc to back out of it and that crashed me as well

then i upgraded them to iron version thinking maybe that would help but those crash me as well
```

This crash is happening to only her (no one else is affected), and only on this server (it doesn't happen to her on my other server which also has Iron Backpacks).

I understand there's nothing really you can do about this, but I thought you should be made aware. I plan to update the mods, forge and SpongeForge at some point in the next week, if this fixes the issue, I will let you know.

#### Crash Report

https://pastebin.com/GXWF0xzk

#### Affected Versions:

- IronBackpacks: 2.2.27
- Minecraft: 1.10.2
- Forge: 2281
- SpongeForge: 5.2.0-BETA-2371
- Modpack: [Dragon Industries 3](https://www.technicpack.net/modpack/172-dragontech-testserver.408937) 

- Alice Sellars
DragonTechMC

**Comment by gr8pefish** [comment]
Hmm, very strange. Does she have her keyboard setup in a unique fashion?

Is the other server the same modpack or a different one?

**Comment by yepidoodles** [comment]
She had different keybindings but resetting them didn't stop the crashes.

Yes the other server is another modpack: https://www.technicpack.net/modpack/elbeta.705651

**Comment by orionSquared** [comment]
I'm actually having this same issue. Playing Beyond on a server with some friends. I can equip my backpack and open it just fine, but if I try to leave the backpack, I immediately crash to desktop. It's happened 5 times in a row. I've tried crafting a new one, cheating one in. Nothing has helped. Everyone else on the server can use their backpacks just fine.

I'm also playing Craft of the Titans single player and am having no issues using my backpack on that pack.

**Comment by gr8pefish** [comment]
Hmm, it sounds like it may be some form of keybinding conflict; I'm not sure.

@orion74656 Can I get your crash report?

**Comment by choekstr** [comment]
Here's my crash report when this just happened to me: 
https://pastebin.com/gz04fc2m (hitting shift)
https://pastebin.com/f2BWJwnN (opening backpack and then hitting esc right away)

I am on US keyboard, running FTB Beyond Single Player, 10.10.2-2.2.27 version of Iron Backpacks and opened the backpack and went to shift click a stack in and it CTD'd.  It seems this happens regardless of if I am wearing the backpack or if I have it in my inventory and right click it.

I don't have any keybinding macros or even a smart keyboard with controlling software (ala Razer, etc) but have done a few keybind changes and removed some conflicts.  I use V for putting on backpack and X for accessing.

Hope this helps.

**Comment by TehNut** [comment]
Interesting. I'll add a check for this when I get home.

**Comment by choekstr** [comment]
Any luck replicating?  I'm dying without my iron backpack mod!  ;)

**Comment by TehNut** [comment]
Sorry, I totally forgot. Got caught up in the summer anime hype.

**Comment by Aanika** [comment]
So im the player this thread was originally started about ive tried quite a few things to find a fix/work around for this and have come up with nothing but i thought i would share a bit more information.

I use a Razer keyboard which only runs when i run the software razer synapse at all times. i have to wonder if this has something to do with it since i am the only one on the server having this issue. 

I can open all types of iron backpacks but pressing escape, e or shift in any type crashes me. i tried unbinding all keys and still crashed i tried rebinding e (open/close inventory) to my mouse and i still crash. so far this server and a new one run by yepi are the only places ive had this issue and one other people on the server dragon industries said they had the issue as well other than that everyone else on these servers is fine. which would make me think it is on my end but i have run iron backpacks on many other servers with no issues. including Everlands which yepi also runs and as one of the other posters said craft of the titans.

if there is any more info i can give you or things i can try please let me know.

**Comment by Aanika** [comment]
oh i started playing on Arcana technologies this morning and crashing there is what promted me to post here. here is the crash report for that (this is on a seperate server than the original crash) not sure if it will help =/
[crash-2017-07-10_15.36.59-client.txt](https://github.com/gr8pefish/IronBackpacks/files/1137011/crash-2017-07-10_15.36.59-client.txt)

**Comment by TehNut** [comment]
Don't worry about it. Right now an array check is going out of bounds any time any key is pressed. I'm going to forcefully make sure this doesn't crash.

**Comment by choekstr** [comment]
And I also run Razer Synapse but for my mouse, not a keyboard.  Seems like this might be a common denominator.  Not sure how an out of bounds array within the game would affect Synapse and crash the game but hey, it might help.  FWIW, I shutdown Synapse and equipped the backpack and it still crashed when I opened the backpack with the hotkey and hit esc to close.

**Comment by orionSquared** [comment]
If it helps, I also run a razor synapse for an external keyboard with joystick for movement. Seems a common denominator but I also use an iron backpack on Craft of the Titans and have no issue.

**Comment by TehNut** [comment]
It's most likely a mod you have in common messing with keybinds.

**Comment by Aanika** [comment]
even when i completely unbound all keys?

**Comment by TehNut** [comment]
The handler is not based on "real" keybinds. It is grabbing an array of all the inventory keybinds (which will be empty in your case) and looping through the index.

**Comment by choekstr** [comment]
I always add in InventoryTweaks and MouseTweaks so perhaps one of those but Direwolf20 and Skyfactory3 packs didn't have an issue with all 3 so I assumed they would be alright still with the latest versions.  I'll test tomorrow with those two removed.

EDIT: Just tested by removing those two mods as a long-shot and that didn't help.

**Comment by Aanika** [comment]
choekstr here is the current server im having trouble with if you want to compare the mod list

https://www.technicpack.net/modpack/arcana-technologies.1054001

**Comment by cha0s** [comment]
Same issue from a user on my 1.10 Beyond server, crash log here: https://cdn.discordapp.com/attachments/323377972814020609/334830912925859850/crash-2017-07-12_17.57.04-client.txt

**Comment by cha0s** [comment]
I should also note that this is the first user out of about 150 that have played on the server that have reported this issue.

**Comment by orionSquared** [comment]
Another odd thing, previously, I was using the iron backpack perfectly fine on Craft of the Titans. Now, since we updated the server, my iron backpack is crashing me to desktop.

**Comment by Aanika** [comment]
If anyone has any information on why this crashes some people and not others and how we can make it not crash us please let us know =( i miss my iron backpacks <3

**Comment by Lynxn** [comment]
Hey,

Same problem with this in the All The Mods Expert v1.1.1 pack
I checked if there was an update for the mod, but currently it is up to date and this problem is still happening. (IronBackpacks-1.10.2-2.2.27.jar)
It happened with the leather backpack and diamond backpacks (The only ones I used, crafted through the other tiers)
I have included the crash report below. Thanks in advance for anything you do about this. :P
[crash-2017-07-16_01.53.04-client.txt](https://github.com/gr8pefish/IronBackpacks/files/1150861/crash-2017-07-16_01.53.04-client.txt)

**Comment by gr8pefish** [comment]
Sorry for the delay; I was away on vacation and had no access to my development environment. I just got back so I'll try and fix this asap for y'all and push a build out soon as well so you don't have to wait any longer.

**Comment by choekstr** [comment]
version 2.2.27 also has the same issue on Invasion modpack.  I did however find that the 2.2.26 version works great in Invasion (haven't tested other packs yet) so I have reverted and can use the wonderful backpacks until gr8pefish has a chance to come out with a new version and fix.

**Comment by gr8pefish** [comment]
Once again, sorry for the delay on this one, the issue just cropped up right before I was traveling. I'm going to try and fix some other things and push them out with this in an update ~~tomorrow~~ now.

**Comment by yepidoodles** [comment]
I just wanted to confirm that the fix did indeed work. Thank you for your help and dedication :)

**Comment by gr8pefish** [comment]
Glad to hear it! :D
