### ISSUE TITLE
Backpack options panel appears during quick deposit

### ISSUE THREAD

**Issue by Rhykes** [gr8pefish/IronBackpacks#182]
While attempting to use Quick Deposit or Precise Quick Deposit (Shift+Right Click while looking at an inventory), the Upgrade Options menu (also Shift+Right Click) appears, although Quick Deposit appears to work as normal. This did not happen in v1.10.2-2.2.27.

Although minor, trying to quick deposit many things into a number of different chests, it becomes an extremely annoying issue.

#### Affected Versions
- IronBackpacks: 1.10.2-2.2.28
- Minecraft: 1.10.2
- Forge: 12.18.3.2297

**Comment by gr8pefish** [comment]
Fixed in new version, should be up on CurseForge momentarily.
