### ISSUE TITLE
Feature Request: Advanced Restocking

### ISSUE THREAD

**Issue by aryst0krat** [gr8pefish/IronBackpacks#186]
While restocking works great on its own, there's a small problem that arises when using it in combination with other mods. Not a bug, just something that probably doesn't need to be considered otherwise.

I'm using a wand to place a lot of dirt, and restocking doesn't seem to understand that the dirt is being used. Theoretically this could be 'fixed', but adding a new upgrade or enhancing the initial one would allow for some workarounds that are also otherwise useful.

A couple suggestions would be to have it always fill a specific slot perhaps by having each slot in the configuration bar represent a hotbar slot (though this one feels like it would be nontrivial), to have it always ensure a certain number of the item are present in the inventory regardless of detecting their use (signified by allowing the ghost items to stack), or to have the option to fill the player's inventory until it can't fit any more.

The first two options seem more useful, but the third seems easier to implement.

You could also potentially somehow allow wands to access backpacks directly, but that may be out of your hands.

**Comment by TehNut** [comment]
This will be solved in the 1.12 rewrite (without a new upgrade) as Mojang added a system for inventory changes we can hook into.

That said, I'm fairly sure there is specific compatibility for wands in place.

**Comment by gr8pefish** [comment]
There is some specific compatibility. I know it works perfectly fine with Better Builders Wands, but it doesn't work at all with Extra Utilities' Building Wands (as they do dumb things internally, and I had to explicitly disable compat to fix a bug with them).

> Allow wands to access backpacks directly

Along with the better ability for inventory change triggers, I hope to have a reliable API others can use for this in the 1.12 rewrite as well.

In all honesty, I wouldn't expect to see this for 1.10, and it is already integral to 1.12, so I'm closing the issue. Thank you for your suggestions though! 👍
