### ISSUE TITLE
[1.10] Quick Deposit Opens Upgrade Options Menu 

### ISSUE THREAD

**Issue by scotty9090** [gr8pefish/IronBackpacks#188]
Similar issue to #182 - Upgrade Options menu opens when shift-r-clicking on an inventory with the backpack in hand, except I'm not getting anything deposited, just the upgrade options menu opening.  

I know this issue is flagged as fixed, but nevertheless I'm still encountering it.  I've used this functionality successfully in the past so I'm reasonably sure I'm doing everything correctly.

Versions:
Minecraft 1.10.2
Forge: 12.18.3.2316
Iron Backpacks:  1.10.2-2.2.31 (also tried with 2.2.29 where this issue is listed as fixed, still no luck.)

Also, just wanted to say, independent of this issue, this mod is wonderful - thank you for your efforts on it.

**Comment by gr8pefish** [comment]
Thanks for the bug report.

Yup, entirely possible I imply broke that functionality while trying to fix something else. Seems to be the case for 1.10, hence the rewrite for 1.12 ;)

Anyways, I'll look into it.

**Comment by gr8pefish** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix all 1.10 issues](https://trello.com/c/084BcvEF/4-fix-all-110-issues)

**Comment by gr8pefish** [comment]
I can't replicate this. Video [example](https://streamable.com/rtn3x). Did your backpack have a depth upgrade on it?

More info is needed for this to be fixed.
