### ISSUE TITLE
Client sometimes crashes when renaming backpacks

### ISSUE THREAD

**Issue by redbaron148** [gr8pefish/IronBackpacks#189]
#### Background:
This is on a private server running a custom modpack of my own creation.  I host a small server for a few of my friends and I to play.  I have not personally seen this crash but two of my friends have both crashed their clients due to this issue.

#### Issue Description:
Occasionally minecraft crashes to desktop when renaming backpacks.  I have not been able to identify what exactly about renaming causes the crash.  It does not seem to be related to the name chosen or the type of backpack or what upgrades are on the backpack.  After they crashed and restarted they were able to name their backpack just fine.

#### What happens:
On clicking enter on renaming a backpack occasionally the client crashes.

#### What you expected to happen:
The backpack to be renamed without crashing.

#### Steps to reproduce (important):
As I previously stated, this does not seem to be consistently happening, but it has happened twice when renaming a leather backpack with no upgrades.  

I don't really expect this report alone to result in a fix, I merely wanted to draw attention to this in case others have a similar issue.  I have attached the crash log from the client in case their is an obvious cause.
[crash-2017-09-05_23.49.09-client.txt](https://github.com/gr8pefish/IronBackpacks/files/1282540/crash-2017-09-05_23.49.09-client.txt)

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.10.2-2.2.31
- Minecraft: 1.10.2
- Forge: 12.18.3.2422
- Other Conflicting Mods (may be irrelevant to your issue): I am happy to provide my modpack on request via a PM.

**Comment by TehNut** [comment]
Probably won't happen in 1.12 since we're doing a from-scratch rewrite. Not sure if gr8pe still plans on supporting 1.10.

**Comment by redbaron148** [comment]
Fair enough.  Again, I didn't really expect such an unrepeatable bug report to actually result in a fix.  Thanks!

**Comment by gr8pefish** [comment]
Weird. Yeah, unfortunately I don't think I'll get to this realistically; there are just too many bigger fish to fry. Regardless, thank you for the bug report!
