### ISSUE TITLE
[1.10] Restocking Upgrade Using Up 2x Resources

### ISSUE THREAD

**Issue by Xuhybrid** [gr8pefish/IronBackpacks#190]
#### Issue Description:

Restocking upgrade uses double the resource amount. Tested with cobblestone and wood.

#### What happens:

With a Restocking upgrade in an Iron tier backpack, when placing an item into the world, an item is consumed from both my hand and the backpack.

#### What you expected to happen:

When used with a filter, if i break and place a block repeatedly, i expect to have the same amount of blocks as when i started.

#### Steps to reproduce (important):

1. Craft an iron tier backpack
2. Add a restocking upgrade
3. Set a filter for cobblestone/wood
4. Place cobblestone inside backpack
5. Place item and look inside the backpack which is now missing 2 blocks instead of 1

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 2.2.27
- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- Other Conflicting Mods (may be irrelevant to your issue): Sky Factory 3

**Comment by gr8pefish** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix all 1.10 issues](https://trello.com/c/084BcvEF/4-fix-all-110-issues)

**Comment by gr8pefish** [comment]
I can't reproduce, may be a conflicting mod or something else. [Video proof](https://streamable.com/p2hu4).

Can you provide any more information?
