### ISSUE TITLE
1.10.2 Crash, not sure if this mod but NEI/JEI crashes when typing @ir

### ISSUE THREAD

**Issue by RepoDraghon** [gr8pefish/IronBackpacks#192]
#### Issue Description:
Either Iron Backpacks or Iron Chests or some other mod is causing this and no one will read and tell me what it is in the crash logs... I'd really like it if someone could teach me how to read the logs so I don't have to ask what mods are crashing...

#### What happens:
When Typing @iron when I type the r, game crashes

#### What you expected to happen:
Items sort by mod

#### Steps to reproduce (important):

1. get Direwolf and Hermit packs, plus a few more, combine, upgrade everything (not sure if you can download my pack from Curse, dunno how to upload it if I have to do that 1st but my username is RepoDraghon)
2. Search NEI for @ir

____
#### Affected Versions (Do *not* use "latest"): 2.2.31 (Latest I can get from the Curse (now Twitch app))

- IronBackpacks: 2.2.31
- Minecraft: 1.10.2
- Forge: = or < 2488
- Other Conflicting Mods (may be irrelevant to your issue): Noted above...
Mods below, files below that

![javaw 2017-09-29 16-28-30-32](https://user-images.githubusercontent.com/8423696/31039580-955cf7a4-a533-11e7-8854-709243c2f956.jpg)
![javaw 2017-09-29 16-28-43-98](https://user-images.githubusercontent.com/8423696/31039583-9562d5b6-a533-11e7-8053-7d4a9e065f3e.jpg)
![javaw 2017-09-29 16-28-51-69](https://user-images.githubusercontent.com/8423696/31039582-955f59cc-a533-11e7-987d-8fff46769c2c.jpg)
![javaw 2017-09-29 16-29-09-04](https://user-images.githubusercontent.com/8423696/31039581-955dd192-a533-11e7-8715-9b582e974b03.jpg)
![javaw 2017-09-29 16-29-23-22](https://user-images.githubusercontent.com/8423696/31039592-958ceff4-a533-11e7-92eb-ee0d480639b5.jpg)
![javaw 2017-09-29 16-29-32-04](https://user-images.githubusercontent.com/8423696/31039584-95662f7c-a533-11e7-84a4-13a683d620c1.jpg)
![javaw 2017-09-29 16-29-40-87](https://user-images.githubusercontent.com/8423696/31039588-9576c968-a533-11e7-8989-cf9540189597.jpg)
![javaw 2017-09-29 16-29-48-18](https://user-images.githubusercontent.com/8423696/31039585-9573c114-a533-11e7-96dc-ba4f5caea36c.jpg)
![javaw 2017-09-29 16-29-52-51](https://user-images.githubusercontent.com/8423696/31039587-95753206-a533-11e7-9581-8428aa76d798.jpg)
![javaw 2017-09-29 16-29-57-97](https://user-images.githubusercontent.com/8423696/31039586-957432fc-a533-11e7-9e9a-0246a131d607.jpg)
![javaw 2017-09-29 16-30-04-24](https://user-images.githubusercontent.com/8423696/31039589-957a69f6-a533-11e7-9a82-6d40ea70788a.jpg)
![javaw 2017-09-29 16-30-14-74](https://user-images.githubusercontent.com/8423696/31039591-958b58a6-a533-11e7-89c7-1ef70c179a30.jpg)
![javaw 2017-09-29 16-30-20-58](https://user-images.githubusercontent.com/8423696/31039590-9589f5ba-a533-11e7-9784-26bdfed98389.jpg)
![javaw 2017-09-29 16-30-24-50](https://user-images.githubusercontent.com/8423696/31039593-95911ef8-a533-11e7-96e8-3b35af61fb3a.jpg)

[fml-client-latest.log](https://github.com/gr8pefish/IronBackpacks/files/1345892/fml-client-latest.log)
[latest.log](https://github.com/gr8pefish/IronBackpacks/files/1345891/latest.log)
[crash-2017-09-29_15.57.17-client.txt](https://github.com/gr8pefish/IronBackpacks/files/1345893/crash-2017-09-29_15.57.17-client.txt)

**Comment by TehNut** [comment]
If you read just the first line of the crash, you would see this has nothing to do with Iron Backpacks.

```
java.lang.NoSuchFieldError: field_78286_d
	at malte0811.industrialWires.client.panelmodel.RawModelFontRenderer.func_78266_a(RawModelFontRenderer.java:51)
```

**Comment by RepoDraghon** [comment]
Freaking awesome, I dont know how to read java error logs so this went right over my head...
