### ISSUE TITLE
[1.10] Restocking Upgrade Deleting Items

### ISSUE THREAD

**Issue by Crystallyne** [gr8pefish/IronBackpacks#193]
#### Issue Description:
When using the Restocking Upgrade on a backpack, it sometimes causes all items of that type to completely disappear from that backpack!!

#### What happens:
This has happened to me at least twice now.  I add a specific block to the "Restocking Upgrade" portion of my backpack, and after placing only a few blocks of that type, the blocks stop being restocked.  I then check my backpack and those specific blocks have ALL VANISHED!!  I've usually had multiple stacks of that item, and barely barely go through a single stack before they all just disappear into thin air!

#### What you expected to happen:
This should be obvious, but I expect to have those blocks remain secure in my backpack, while constantly feeding me a supply of those blocks on my hot bar, until I legitimately run out of blocks.

#### Steps to reproduce (important):

1. Add Restocking Upgrade to bag.
2. Fill bag with the blocks I want to keep restocked on my hot bar.
3. Take out my first stack and place on hot bar.
4. Shift-Right Click to edit the backpack.
5, Add the block to the Restocking Upgrade.
6. Begin placing blocks.
7. At some point, usually not long after adding the blocks to the restocking upgrade, I notice the blocks are no longer being restocked.  Open the backpack and find ALL of the blocks of that type have disappeared.

Note: The only other upgrade I have on this bag is the Basic Filter.  I have filled this bag with a bunch of torches, as well as Clear Glass blocks (from Tinkers' Construct).  I did add torches to the Basic Filter, but I did NOT add the Clear Glass to the Basic Filter.  I just went back and double checked, and realized that all of my torches have vanished, as well as my Clear Glass blocks.  So it seems that having the items listed in the Basic Filter, in addition to the Restocking Upgrade, does not make a difference.

This also happened with a whole bunch of wood blocks I had collected, while trying to build my base.  A dozen stacks of wood...all vanished into thin air.
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 2.2.31
- Minecraft: 1.10.2
- Forge: Invalid?  I am playing through the Curse/Twitch App.  I'm using the FTB Infinity Lite 1.10 Mod Pack.  I added Iron Backpacks to the mod pack, myself.
- Other Conflicting Mods (may be irrelevant to your issue):  Aside from the mods that come with the FTB Infinity Lite Mod Pack, the only other mods I added manually are an Auto Run mod, and Roguelike Dungeons.  

I'm sorry, I have not tried to eliminate other mods to see if there is a conflict, because I'm playing it through the Twitch app.  If you really need me to try this, I can give it a go.  But I'm hoping I am able to provide enough information to track down the problem...

I really love this mod, but this issue with my backpack devouring items I really need has been a huge headache for me.  I'll just stop using the restocking upgrade for now, but hope that I can help identify what the problem is.

![image](https://user-images.githubusercontent.com/32418385/31047839-ab3d88c0-a5c6-11e7-80e9-518a1ed40710.png)
![image](https://user-images.githubusercontent.com/32418385/31047858-f9c6a0e4-a5c6-11e7-8470-bea4eb78ce81.png)

**Comment by gr8pefish** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix all 1.10 issues](https://trello.com/c/084BcvEF/4-fix-all-110-issues)

**Comment by gr8pefish** [comment]
Hmm, thanks for the detailed report. Unfortunately, I cannot reproduce the issue.

Here's a [video ](https://streamable.com/wicpq)of me placing 60 blocks (I also tested with 120) and it working just fine, let me know if you did anything different.
