### ISSUE TITLE
Not working in 1.12, MC launcher says it's 1.12.2

### ISSUE THREAD

**Issue by IbenPerson** [gr8pefish/IronBackpacks#195]
#### Issue Description:
When downloading the mod, it says it's for 1.12, 1.12.1 and 1.12.2, and I'm playing in 1.12.

#### What happens:
The Minecraft launcher says it's for 1.12.2

#### What you expected to happen:
I thought it would work for 1.12, am I doing it wrong?

#### Steps to reproduce (important):

1. Have an instance in MultiMC with 1.12
2. Add Iron Backpacks for 1.12, 1.12.1 and 1.12.2
3. MC launcher telling me it can't run it because Iron Backpacks is in 1.12.2
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.12.2-3.0.0.jar
- Minecraft: 1.12
- Forge: 1.12-14.21.1.2443
- Other Conflicting Mods (may be irrelevant to your issue): None

**Comment by IbenPerson** [comment]
I really like this mod, and I've been waiting for this update :-) so I really hope to get a version I can use in 1.12 :-)

**Comment by gr8pefish** [comment]
You are correct, it should work but the jar you have specifically need 1.12.2. I changed the versioning label on CF so others hopefully aren't confused in the meantime. 

It is a minor issue, so @TehNut should be able to fix it and get a 1.12.x version out when he has time to do so.

**Comment by IbenPerson** [comment]
Cool, I'll look forward to it :-)
