### ISSUE TITLE
Iron Backpack - Possible Dupe

### ISSUE THREAD

**Issue by Keaton1188** [gr8pefish/IronBackpacks#196]
#### Steps to reproduce (important): Wasn't able to.

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks:  IronBackpacks-1.10.2-2.2.31.jar
- Minecraft:  1.10.2
- Forge:  12.18.3.2488

**Comment by gr8pefish** [comment]
That's super strange, and is almost certainly a mod interaction issue. I'm sorry, but without replication it is near impossible to fix. If you do give more information I'd be happy to revisit the issue though.

Thanks you for the bug report.
