### ISSUE TITLE
Conflict with InventoryTweaks ? v. 1.12.2

### ISSUE THREAD

**Issue by Dockter** [gr8pefish/IronBackpacks#197]
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.12.2-3.3.0
- Minecraft: 1.12
- Forge: 1.12.2 - Build 2509.
- InventoryTweaks: 1.63

- Other Conflicting Mods (may be irrelevant to your issue):
Also using SpongeForge - 1.12.2-2503-7.0.0-BETA-2696.

Thank you,

**Comment by Xiaminou** [comment]
I think this issue is that there is currently no InventoryTweaks support for this version and therefore you can't use its shortcuts.
Or is it a bug?

**Comment by TehNut** [comment]
I wasn't really able to reproduce this, but I have gone ahead and reimplemented the InvTweaks API in 7fb26c07680d669d7428b2730d7a428951ac470e which should solve any issues. If it persists, I'm going to chalk it up to Sponge unless you can prove otherwise.
