### ISSUE TITLE
new [Idea] allow multiple filter upgrades 

### ISSUE THREAD

**Issue by kurokuno** [gr8pefish/IronBackpacks#2]
ok so when having mods like say metallurgy installed you end up with like 30+ ores and one filter fills up fast i know you have a mod filter however then vanilla ores only becomes an issue i would be more than happy to sink multiple filter upgrades into my diamond pack but i noticed it was capped to 1 per bag was just wondering if that could be changed or a config option

**Comment by gr8pefish** [comment]
Already thought about that and am currently working on adding in more filter slots :)
