### ISSUE TITLE
[Bug?] Upgrading a backpack deletes its contents

### ISSUE THREAD

**Issue by ManMan36** [gr8pefish/IronBackpacks#200]
#### Issue Description:
Whenever you upgrade a backpack to a higher level and the backpack has anything inside of it, the resulting backpack will be empty. Is this a bug or an intended feature, because I don't really know.

#### What happens:
You lose your stuff and can't get it back.

#### What you expected to happen:
I was expecting the backpack to retain its contents when upgraded.

#### Steps to reproduce (important):

1. Acquire a leather backpack.
2. Put items in said backpack
3. Upgrade backpack to iron (either storage emphasis or upgrade emphasis)
4. Open backpack
5. Rage and put fist through computer screen.

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 3.0.0
- Minecraft: 1.12.2
- Forge: 14.23.0.2512
- Other Conflicting Mods (may be irrelevant to your issue): Most likely irrelevant (this was reproduced in a world that had only Iron Backpacks, JEI, Light Level Overlay Reloaded, and Journey Map)

**Comment by TehNut** [comment]
Not yet implemented.
