### ISSUE TITLE
Game Crashes When Using Nested Quick Deposit Upgrade

### ISSUE THREAD

**Issue by zoomiti** [gr8pefish/IronBackpacks#206]
#### Issue Description:
When using a backpack with quick deposit inside a backpack with depth and nesting upgrades, and shift right click a chest with the "nester" backpack, the game crashes. After the game crashes and every reload there-after shift right clicking the "nester" backpack crashes the game. 

#### What happens:
Game crashes after triggering bug and every time you shift right click nester-backpack.

#### What you expected to happen:
Contents from nested backpack get moved to the chest when using shift right click on "nester backpack".

#### Steps to reproduce (important):

1.  Apply quick deposit to iron backpack and apply advanced nesting upgrade, and depth upgrade to diamond backpack.
2.  Fill the iron backpack with items.
3.  Nest the iron backpack inside the diamond backpack.
4.  Shift right click the diamond backpack on a chest.

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.2.20
- Minecraft: 1.7.10
- Forge: 10.13.4.1614
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by zoomiti** [comment]
Note: may be similar to issue #191 as it's only happened with a diamond "nester" backpack

**Comment by TehNut** [comment]
Sorry, we're not accepting issues for 1.7.10, anymore!
