### ISSUE TITLE
[1.10] Tiny Grammatical Error

### ISSUE THREAD

**Issue by ghost** [gr8pefish/IronBackpacks#208]
There’s a grammatical error in the description of the quick deposit upgrade and the precise quick deposit upgrade: “it’s” instead of “its.”

**Minecraft version**: 1.10.2
**Iron Backpacks version**: 2.2.36

**Comment by gr8pefish** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix all 1.10 issues](https://trello.com/c/084BcvEF/4-fix-all-110-issues)
