### ISSUE TITLE
Upgrades for backpacks not showing up in NEI

### ISSUE THREAD

**Issue by masterterp** [gr8pefish/IronBackpacks#211]
Issue Description:
While in the NEI database the upgrades for iron backpacks were not showing up. 
There only three upgrades available. More upgrade points, Latch upgrade, and damage bar upgrade. None of the filters or the Nesting upgrades were showing up

Steps to reproduce (important):

1. open NEI database from your inventory
2. search for iron backpacks in the search bar
3. only a few upgrades for the backpacks show up
________________________________________
Affected Versions 

- IronBackpacks:  1.12.2-3.02-3
- Minecraft: 1.12.2
- Forge: 14.23.1.2555
________________________________________
Screen shot

![2018-01-01_03 08 01](https://user-images.githubusercontent.com/34935607/34466949-8a9070d2-eea1-11e7-83e4-ba0e503270fa.png)

____________________________________________________________________________________________________________
Log File

[2017-12-31-2.log.gz](https://github.com/gr8pefish/IronBackpacks/files/1595838/2017-12-31-2.log.gz)

**Comment by AMartinie** [comment]
Because 1.12 is a dev build. The filter upgrades haven't been released yet.

**Comment by masterterp** [comment]
oh thnx sorry
