### ISSUE TITLE
[1.12.2] Crash When Changing Key Bindings

### ISSUE THREAD

**Issue by GWSheridan** [gr8pefish/IronBackpacks#213]
When changing keybindings soon as click the controls button MC will crash

crashes game to launcher

steps to reproduce (important):

1. Update to newest version
2. load up
3. go in game world then change some keybindings 
4. does not effect in game main menu

- IronBackpacks: 3.0.3
- Minecraft: 1.12.2
- Forge: 14.23.1.2590

**Comment by TehNut** [comment]
Could you provide the crash log?

**Comment by TehNut** [comment]
Ah, @gr8pefish, you only disabled the registration of the keybinds. You didn't actually disable them. That's a nono.

**Comment by gr8pefish** [comment]
Ah, sorry.

Thanks for the hotfix; I'll push out a new version later today.
