### ISSUE TITLE
[1.12.2] Deleting issue

### ISSUE THREAD

**Issue by yepidoodles** [gr8pefish/IronBackpacks#216]
When a backpack is open, and you hold an item using your cursor and then close the backpack, the item you're holding is deleted. 

- IronBackpacks: 3.0.4
- Minecraft: 1.12.2
- Forge: 14.23.1.2594
- SpongeForge: 2555

**Comment by gr8pefish** [comment]
Can you reproduce this without SpongeForge?

**Comment by TehNut** [comment]
Cannot reproduce in neither SSP nor SMP.

**Comment by yepidoodles** [comment]
Tried to replicate on Single player, but it doesn't happen there. Seems to be an issue only on the server.

**Comment by TehNut** [comment]
I wasn't able to reproduce on a only Forge server. Can you try without Sponge.

**Comment by yepidoodles** [comment]
I'm running this on a public server and don't have the resources for a test one :/ So I can't

**Comment by gr8pefish** [comment]
I don't want to sound callous but in all likelihood I'm going to ignore this issue until it is tested on a Sponge-less server. I'd like to commit more time to it, but I've got a full plate as-is. If you do get the chance to test it (even real quick), please let us know the results and I'll gladly reopen the issue if need be.

**Comment by yepidoodles** [comment]
I understand completely, I'll see what I can do, thanks anyway.

**Comment by yepidoodles** [comment]
This was a Sponge issue, which is now fixed :)

**Comment by gr8pefish** [comment]
Good to know, thanks 👍
