### ISSUE TITLE
[1.12.2] Pressing the number key while mousing over secondary bag in hotbar causes 'nested' backpacks

### ISSUE THREAD

**Issue by luke-bravenboer** [gr8pefish/IronBackpacks#217]
Replicated with only Iron Backpacks 1.12.2-3.0.4 & Forge 14.23.1.2575 installed.

- Requires two backpacks in your hotbar

Open the first one, mouse over an inventory spot in the open backpack, then press the number key on your keyboard that corresponds to the hotbar slot that the second backpack is in, causing the second backpack to be inserted into the first backpack; however, there is no apparent way to remove it!

Affects all backpack types & emphasises. (_Emphases? Emphasis'? What the heck is the plural of 'emphasis'_)

**Comment by TehNut** [comment]
Was literally about to push a fix for this. I was typing up a haiku in the commit message.

**Comment by luke-bravenboer** [comment]
Oh well done, don't let me interrupt your haiku! :P

**Comment by TehNut** [comment]
I'll let gr8pe push a build whenever he wakes up. I don't know what else he wants done first.

**Comment by gr8pefish** [comment]
Pushing out a new build now; sorry for the delay. New version should be up on CF momentarily (pending approval now).
