### ISSUE TITLE
Backpack stuck Issue

### ISSUE THREAD

**Issue by Klen97** [gr8pefish/IronBackpacks#219]
#### Issue Description:
When I have like 2 backpack: 
If I open backpack1, and backpack2 is in my hotbar, when I press the button which is assigned to that slot (and my arrow is in backpack1) the backpack2 is goes into the backpack1 and stuck in it.
It's in the revelation pack. (And in it the nest upgrade forbidden)

#### What happens:
The backpack stuck in another one.

#### What you expected to happen:
It should be reversible, or it shouldn't happen.

#### Steps to reproduce (important):

1. Get a Diamond backpack without any upgrades
2. Get a Gold backpack without any upgrades
3. Both Backpack have to be on your hotbar
4. Open the Diamond one
5. Bring the cursor into the Diamond backpack storage screen
6. press 1 if the gold backpack is in your first place on the hotbar
7. Try to get out the gold backpack ;)

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 3.0.4
- Minecraft: 1.12.2
- FTB Revelation: 1.4
- Forge: 14.23.1.2601
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by TehNut** [comment]
Update
