### ISSUE TITLE
TehNut/gr8pefish internal chat

### ISSUE THREAD

**Issue by gr8pefish** [gr8pefish/IronBackpacks#22]
@TehNut 
Just making this issue so that we can easily ping each other to talk about anything.

Have you seen that I added you as a contributor to the curseforge project? This means you can add your 1.8 builds to it without having to go through me.

Also, I think I would like to add some form of tick handler to handle the restocking upgrade, instead of checking for it when the onItemPickupEvent fires. However, I want to do it right, I don't want to add unnecessary computational strain with this mod, so if I do it and tag you in the commit to remind you, could you check over it to make sure I'm doing it at least semi-efficiently?

Also, I updated the MCF page, and will make a posting in the next couple of days on r/feedthebeast about the updates (both 1.8 and 1.7).

**Comment by gr8pefish** [comment]
Closing so it doesn't clog up the open issues for others. We can still comment on it though, obviously.

**Comment by TehNut** [comment]
Heh, I was thinking about doing this earlier today :p

> Have you seen that I added you as a contributor to the curseforge project?

Yes, I did, thank you.

> This means you can add your 1.8 builds to it without having to go through me.

I meant to ask, how do you want me to handle version numbers? Should I just continue with `1.0.5`, `1.0.6`, etc? Or should I do build numbers (`1.0.4-2`, 1.0.4-3`, etc) until you advance the version?

> so if I do it and tag you in the commit

Ping me in any commit you want me to look at. I'll do the same.

Also, locking it so just we can talk here.

**Comment by gr8pefish** [comment]
> I meant to ask, how do you want me to handle version numbers? 

Do whatever you feel is necessary, if it seems like a big change then feel free to do it without the build numbers (that is what I am doing but since we have different styles it may be different for you). To keep it relatively consistent maybe look at what I am doing. Just small updates are 1.1.x and big ones are 1.x, but you can change it a little if it suits you. Not that big of a deal either way :)

> Ping me in any commit you want me to look at. I'll do the same.

Sounds great.

P.S. I am in the timezone of Stockholm, so just look at what time it is there to make a guess as to if I am up or not. Also, after today (so 15 hours or so from now since my day just began) I will be out away from internet for 4 days; just giving you a heads up.

**Comment by TehNut** [comment]
Can do for versions. I'm in PST. 

Also, [here](https://github.com/gr8pefish/IronBackpacks/blob/devSweden/src/main/java/main/ironbackpacks/ModInformation.java#L11), that version is used for Forge's internal versionizing. It _is_ needed. How you currently have it, anybody can join a server with any version of the mod because Forge won't see them as different. A simple change to `@VERSION@` will make it auto-replaced with your buildscript's version.

And [here](https://github.com/gr8pefish/IronBackpacks/blob/devSweden/src/main/java/main/ironbackpacks/ModInformation.java#L15) you specify a ConfigGuiFactory in `main.ironbackpacksclient.gui.config` but there isn't one there. The only reason I mention it is because you removed the comment that disabled it in ad2d455338cd300ee22b2d0deefc9455e54b3f3f

**Comment by gr8pefish** [comment]
Thanks for the catch on the versioning, I did not know that.

As it is right now the ConfigGuiFactory just does nothing when you press the button to go to it in the options menu. Not a big deal, as it doesn't cause a crash or anything (just logs an error), but I will disable it again.

Also, I'm totally stealing that awesome building script you just put in (on the 1.8 branch), that's nice :D

**Comment by TehNut** [comment]
To use those buildscript features, just run `gradlew clean build curseforge` to upload as a beta, and `gradlew clean build curseforge -Prelease` to upload as a full release. Also, [create yourself an API token](http://minecraft.curseforge.com/account/api-tokens) on CurseForge and add `curse_key=YOURTOKEN` to `.gradle/gradle.properties` in your home Gradle folder (defaults to `C:\Users\USER\.gradle` on Windows).

**Comment by gr8pefish** [comment]
Just FYI: I am going to be very busy IRL for the next month or so. I leave on Monday for a 1.5 week trip, then I come back and have 1 week before finals and final projects are due, and then shortly after that I fly back to the US and meet my family for Christmas. Long story short, don't be surprised if I seem to disappear during this time. After New Years I should have _some_ time again though :P

**Comment by TehNut** [comment]
No worries. I'll be gone for a bit of December as well.

I added a `code complete` label for issues. When you push a fix for an issue, set that label and keep the issue open. This lets the reporter know that it has been solved. When you push a release with that fix, then close the issue.

**Comment by TehNut** [comment]
Brought the Curse uploading/changelog stuff over to `devSweden`

**Comment by gr8pefish** [comment]
Thanks for the `code complete` label, it's a good suggestion.

I have been doing a lot of work on the mod recently and I want to push out more smaller releases so I changed the build.gradle to increment version numbers so it will look like Botania's versioning: 
(IronBackpacks-r1.7.10-[buildNumber]). 
The build.gradle doesn't work flawlessly yet (I made a lot of changes and I don't understand gradle yet), but it is close to functional. Issues with it are [here](https://github.com/gr8pefish/IronBackpacks/blob/2b2bb9f6d2477346ee552fed3bab5b8ebd4c2de9/src/main/java/main/ironbackpacks/util/Ideas#L5) that I will fix, but there is the link just so you know about the issues if you plan to use it in the meanwhile.

The `devSweden` branch is now the main branch I work off of, `master` is basically unused at this point. I would like to do a PR and merge `devSweden` into `master`, but since `devSweden` was a branch of `dev` the two (`devSweden` and `master`) are too different to do a PR and merge (modding is a learning experience for me, I know now that what I did with the branches isn't ideal). What is the best way to fix this, just have master point to what `devSweden` is now?

Also, I leave for Budapest in a couple hours, so I will probably disappear for a week and a half. Cheers!

**Comment by TehNut** [comment]
Settings > Branches > Default Branch

As for Curse, you're using the ForgeGradle `curse` task (outdated and deprecated) instead of the CurseGradle `curseforge` task. All you really needed to do was change the version string. Not too sure what you're even trying to accomplish with any of the other changes.

**Comment by gr8pefish** [comment]
Thanks.

Haha it looks like it is obvious that I don't know what I'm doing. I made it so that you can run gradle to clean, build, update version, make a new changelog for the next version, and upload the built file to curse in one command. Not all necessary and particularly efficient, to be sure, but I had fun with it and learned about gradle, so no harm done.

**Comment by TehNut** [comment]
Could have just done that with a .bat file :p Want me to set one of those up for you instead?

**Comment by gr8pefish** [comment]
Ah of course, forgot about those nifty things ;)

If you want to do it, I'd be interested in seeing how, but you don't have to if it is much trouble. I do also want to get the gradle one working eventually, at the very least just to learn more about how gradle works.

**Comment by TehNut** [comment]
For Gradle it would just be a single line:

`tasks.curseforge.dependsOn clean incrementVersionNumber build`

Then you would just run `gradlew curseforge`

**Comment by gr8pefish** [comment]
Yes I got that to work, but your way is what I was looking for, the likely accepted and clean way to do it. Will it run in that order or do you have to specify it (i.e. `incrementVersionNumber.mustRunAfter build`)?

**Comment by TehNut** [comment]
It _should_ run in that order.

**Comment by gr8pefish** [comment]
Okay, that's what I thought. Thanks for the assistance!

**Comment by TehNut** [comment]
By the way, I run my own Jenkins server over [here](http://tehnut.info/jenkins/). If you would like me to setup projects for 1.7.10 and 1.8, I will. It also has a [Maven](http://tehnut.info/maven/) to upload to as well.

**Comment by gr8pefish** [comment]
Hmm, I must admit I'm not too well versed in what those do. If my understanding is correct, it is an automated build system so you can commit and the project will attempted to be automatically built (pass/fail). I'm not sure how useful this will be, if you think it is necessary then by all means go for it. Essentially, I don't know enough about it to have a firm decision if it will be really helpful and if I want it, but I do know that I don't _need_ it. You can decide :D

**Comment by TehNut** [comment]
You got it right. And it's definitely not something that has to be done, I just like to have it for my projects and offer it out to anybody.

The one big upside is the Maven which allows other authors to import your mod to their project for usage.

**Comment by gr8pefish** [comment]
Okay. Thanks for the offer, but I think, _for the time being_ I don't need it. Perhaps in a month when I finish study abroad and am back home with more spare time I will change my mind though ;)

I also marked a 1.8 issue for you to fix. I would do it myself, but the hostel I am currently at has super slow internet, so by the time I update the repo you could probably have already fixed it.

**Comment by gr8pefish** [comment]
Just letting you know, [this](https://github.com/gr8pefish/IronBackpacks/blob/b27eb7c507af38e7646fe1bdfd14cddae922f052/src/main/java/main/ironbackpacks/util/Ideas#L41-L56) is semi-accurate for what I plan to do next. Of course, stabilizing/fixing bugs/testing comes before that. Just keeping you in the loop, as starting an API is notable. However, I probably won't get around to that until post-New years, unless some free time magically appears ;)

**Comment by TehNut** [comment]
I was already API-ifying already :p

**Comment by gr8pefish** [comment]
So, FYI, I am going to port a different small other mod to kind of get the hang of 1.8, and then I think I will focus my development on the 1.8 version, as I have the 1.7.10 version in a good state right now. I will still do bugfixes for 1.7.10, but I think, depending how this port goes, I will now do most of my feature work on 1.8. So if you have any uncommited changes or things you are working on for that branch, either push them or talk to me here or whatever! 

Cheers! And great work with the other ports (i.e. Blood Magic) :D

**Comment by TehNut** [comment]
Honestly I haven't had much time to do anything with this lately due to other projects. Feel free to continue on with the 1.8 branch from where it is. I would suggest nuking my failed attempt at the equipping feature and implementing it how you did in 1.7.10. If you have any future questions, don't hesitate to ask!

Have fun and enjoy the port. :p

**Comment by gr8pefish** [comment]
Yup, I kind of figured as much, you have been very busy indeed ;)

I think at some point I may take you up on that offer and ask you future questions as I get stuck, but I'll try to not bug you too much!

**Comment by gr8pefish** [comment]
Okay so I cannot for the life of me figure out why my texture is not working, why I am just getting the pink and black squares for my items. I tried to port something else, using a lot of your code, and I got everything else, but I am stuck on textures. [Here](https://github.com/gr8pefish/PortableCrafting) is the repo.

**Comment by gr8pefish** [comment]
Hey Nut. Hope you're doing well.

I just wanted to give you an update, just in case you were curious, because it can't hurt. Anyways, the reason I have disappeared off the face of the earth (in relation to modded MC) is that I have been super busy with school work recently (3rd year CS degree will do that), and have just not had the energy to devote to modding. When this semester ends (in just over a month), then I hope to get back into it, but we will see.

Cheers!

**Comment by TehNut** [comment]
No worries. I'm still subscribed to the issues here and comments on MCF/Curse so I've seen you mention that.

**Comment by gr8pefish** [comment]
Alright cool. I figured as much, but I wanted to keep you in the loop just in case you were unaware.
