### ISSUE TITLE
Having Iron (Diamond) backpack selected in hotbar lags Minecraft client

### ISSUE THREAD

**Issue by undeadbanana** [gr8pefish/IronBackpacks#220]
Note: Delete the following 2 lines when you submit the issue. (Actually 4 lines. 2 sentences though)

#### Steps to reproduce (important):

1. Grab diamond backpack.
2. Place in hotbar.
3. Lag.
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 3.0.5-6
- Minecraft: 1.12
- Forge: 2601
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by TehNut** [comment]
Define "drastically". Does this happen with only Iron Backpacks installed?

**Comment by undeadbanana** [comment]
Currently using FTB revelations, and just checked. It happens only when it specifically is selected. 

![2018-01-31_13 15 28](https://user-images.githubusercontent.com/4379427/35647917-f495d5c2-0688-11e8-97fb-12d04656620b.png)
![2018-01-31_13 15 33](https://user-images.githubusercontent.com/4379427/35647919-f4b38f04-0688-11e8-8fc1-ea4c71fe3bc1.png)

You can see the ~10fps avg vs 140. My computer specs are there also, not playing on a potato.

**Comment by TehNut** [comment]
>Does this happen with only Iron Backpacks installed?

**Comment by gr8pefish** [comment]
Yeah, isolating that issue is going to require that we confirm that iron backpacks (and nothing else) is causing it.

Nut: Somewhat related -> do you have a Nvidia GPU? I have AMD.

**Comment by TehNut** [comment]
I have a GTX780. I have not noticed this issue. As for CPU, I have an i7-4790k.

**Comment by Ricket** [comment]
Also try the default resource pack, I wonder if maybe that custom backpack geometry is accidentally super complex for example.

**Comment by undeadbanana** [comment]
Ricket, you solved it. Selected the backpack and turned UI off, everything became normal. Contacting creator who patched Sphax for Iron Backpacks.

**Comment by VallenFrostweaver** [comment]
I would like to reopen this issue. I do not use a resource pack and am playing All the Mods 3 v. 5.8 that uses Iron Backpacks v. 3.0.5-6 and just having the diamond backpack on my hotbar drops 5-ish FPS and holding it drops 10-30 FPS. I had other players test this on the server and they had the same results.

**Comment by gr8pefish** [comment]
Any resource packs? What upgrades are on the pack (does that influence it)? I'm afraid I'm going to need more details to have any hope of solving this.

P.S. Nice videos 👍

**Comment by VallenFrostweaver** [comment]
Thanks!
No resource packs. No upgrades but it is a storage focused backpack.

**Comment by gr8pefish** [comment]
Can you duplicate the frame drop with just Iron Backpacks? I need to ensure it isn't a modpack issue.

**Comment by VallenFrostweaver** [comment]
I'll have to make an iron backpacks only pack tomorrow. I've shut things down for the night. I'll get back to you.

**Comment by SilentR33p3r** [comment]
Can confirm only forge and iron backpacks install sees frame drops.

![2018-03-25_21 22 32](https://user-images.githubusercontent.com/37234212/37883960-34c9d058-3073-11e8-9fc5-c5ecc7abbed7.png)

![2018-03-25_21 22 39](https://user-images.githubusercontent.com/37234212/37883967-3b06c08e-3073-11e8-9042-18c4632f5bc2.png)

**Comment by Infraded** [comment]
I've been seeing this also in the DW20 1.12 pack for a bit. When the diamond backpack is out, `root.GameRenderer.level.hand` goes from about 0.7% to 70% overall usage in the CPU graph.

**Comment by Skar78** [comment]
I can report the same issue. Goes from 120 fps to 15 (!). Doesnt matter whats inside.

However holding it in your hand only causes the fps drop **after the first time you open it.**

(Tested this with a new game, SP, went Creative, gave me a diamond backpack.)

**Comment by gr8pefish** [comment]
Thanks. This is high on my priority list of what to fix next.

Edit: It's the coloring code. Will try and get a fix out somewhat soon.

**Comment by Skar78** [comment]
Glad to hear that. Just wanted to elt you know that it only drops after opening, thought that might give a pointer. Thanks for all the hardwork - enjoyed the mod as part of sooo many modpacks.

**Comment by gr8pefish** [comment]
The new version is now live on CurseForge. I believe this issue should now be fixed, but let me know if it somehow isn't.
