### ISSUE TITLE
No controls in Version-1.11.2-3.0.2-3

### ISSUE THREAD

**Issue by MattFishy18** [gr8pefish/IronBackpacks#222]
#### Issue Description:
Can't set a hotkey to equip or look into the bag

#### What happens:
Can't use mod in the way it was showcased

I have tried all the versions available for 1.11.2 and have the same problem for them all

#### What you expected to happen:

The bag to go onto my back

#### Steps to reproduce (important):

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: IronBackpacks-1.11.2-3.0.2-3
- Minecraft: 1.11.2
- Forge: 13.20.1.2579
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by TehNut** [comment]
Probably because they don't exist.

**Comment by MattFishy18** [comment]
So the mod doesn't work then?

**Comment by gr8pefish** [comment]
The showcase was for the 1.10 version. The curseforge page clearly states that a rewrite is occurring and not all functionality may be present.

**Comment by MattFishy18** [comment]
Oh. I had the mod given to me and I am new to modding Minecraft. Didn't know there was a place to read what was going on I was on this page trying to figure it out and couldn't. Thanks for letting me know where to go so I can keep up to date on the mod. I do like what I can see from all the videos about it was just confused as to why it wasn't working.
