### ISSUE TITLE
Can't apply upgrade

### ISSUE THREAD

**Issue by InjuredWolf** [gr8pefish/IronBackpacks#224]
#### Issue Description:
I was trying to apply the Damage Bar upgrade to a Storage Emphasis Diamond Backpack. The usual method of crafting them together didn't work.
#### What happens:
There is no crafting output for the backpack and the upgrade together
#### What you expected to happen:
The items combine into a backpack with the upgrade equipped.
#### Steps to reproduce (important):

1. Craft a backpack (I used a SE Diamond one)
2. Craft an upgrade (I used the damage bar one)
3. Attempt to craft them together
4. Note the lack of output for the crafting.
____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 3.0.5-6
- Minecraft: 1.12.2
- Forge: 14.23.2.2613
- Other Conflicting Mods (may be irrelevant to your issue): None that I know of

**Comment by InjuredWolf** [comment]
Tested with all backpacks with all 4 upgrades, no cigar.

**Comment by TehNut** [comment]
Anvil

**Comment by InjuredWolf** [comment]
Ah. Was not aware. My bad.
