### ISSUE TITLE
[1.12.2] Config option Request.

### ISSUE THREAD

**Issue by Vizis** [gr8pefish/IronBackpacks#226]
Could you add options to make backpacks not craftable?
I mean for every single one.
Cause i think it would be cool to let player craft normal leather backpack, and the rest he could obtain by doing quests on RPG servers like.
I have spongeForge server, and i dont have really much option to block crafting :-1:

**Comment by Vizis** [comment]
Also on 1.12.2 i can't put in on. Both keys in controls says "DISABLED"

**Comment by TehNut** [comment]
Use CraftTweaker.
