### ISSUE TITLE
Just a question! Backpack recovery

### ISSUE THREAD

**Issue by zThundy** [gr8pefish/IronBackpacks#227]
#### Issue Description:
Deleted player inventory

#### What happens:
i accidentally deleted my personal inventory; i noticed that the backapck had an uuid. Can i recover the inside of that backpack at least?

#### What you expected to happen:
^^^^^^

#### Steps to reproduce (important):

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.2.20
- Minecraft: 1.7.10
- Forge: 1.7.10
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by gr8pefish** [comment]
No, unfortunately not. It's planned as an eventual feature, but is not yet implemented (and won't be for a while if I'm realistic).
