### ISSUE TITLE
Framedrops under 40-20

### ISSUE THREAD

**Issue by Kratzwurst** [gr8pefish/IronBackpacks#228]
Hey Folks, i played currently the Direwolf20 pack on Minecraft 1.12.2 on the Version 1.8.0.

#### Issue Description:
The Iron Backpack Diamond drops the FPS under 40-20

#### What happens:
When i take the Diamond Backpack in my Hand, than drops the FPS unter 40-20.
In empty ahnd, restabilzed the FPS to normal.

#### Steps to reproduce (important):

1. I Reporting first this Issue on this Posting: https://forum.feed-the-beast.com/threads/iron-backpack-instant-framedrops.271872/
2. I figured out what's happend. I use some few Ways. without Optifine or Texturepack (Sphax PureDB)
3. Screenshots:
![iron_backpack_diamond](https://user-images.githubusercontent.com/13652826/36770665-e08f28f2-1c4b-11e8-872e-a25c390b0a7b.png)
![iron_backpack_diamond_2](https://user-images.githubusercontent.com/13652826/36770691-fac2c418-1c4b-11e8-9617-53d0c06666d1.gif)

4. FML Latest:
[fml-client-latest.log](https://github.com/gr8pefish/IronBackpacks/files/1765642/fml-client-latest.log)
____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks:  3.0.4
- Minecraft: 1.12.2
- Forge: 14.23.1.2601
- Modpack: Direwolf20 V. 1.8.0
- Other Conflicting Mods (may be irrelevant to your issue): Optifine 1.12.2_HD_U_C9
- Resourcepack:Sphax PureDBCraft for Direwolf20

Greets

**Comment by TehNut** [comment]
#220
