### ISSUE TITLE
i am unable to equip upgrades to the storage backpack in dw20 1.12 modpack

### ISSUE THREAD

**Issue by andwhat11** [gr8pefish/IronBackpacks#229]
i am unable to equip upgrades to the storage backpack in dw20 1.12 modpack. i place backpack in crafting grid along with the damage bar upgrade, nothing shows up in the crafting output. i know this is till in alpha but am i supposed to be able to equip upgrades at this point or am i out of luck when it comes to equiping the upgrade.

**Comment by TehNut** [comment]
Anvil
