### ISSUE TITLE
Upgrades Cannot Be Applied

### ISSUE THREAD

**Issue by Kabaiel** [gr8pefish/IronBackpacks#230]
Upgrades seem to be broken. When I try to search in JEI, I can only find the recipes to create the upgrades, and recipes to use blank upgrades to improve backpack size. There are no recipes for applying others, for example, the damage bar upgrade. Even attempting to run the recipe 'by hand' (crafting grid: insert backpack and damage bar upgrade side by side) produces no results.

I love the mod for the storage space, and eagerly await the other upgrades advertised (filters!), but it would be nice if the existing upgrades could be applied. Is this simply a WIP? Or am I missing something like another mod or a cfg option? The upgrades are showing enabled in the cfg file. 

Versions:
Minecraft 1.12.2
Forge 14.23.2.2611
Iron Backpacks 1.12.2-3..0.5-6
JEI 4.8.5.138 or JEI 4.8.5.147

Don't worry about telling me to dig elbows deep into a cfg file. I worked in IT for decades. Doesn't even make me blink. ;)

**Comment by TehNut** [comment]
Anvil
