### ISSUE TITLE
Backpack in a backpack

### ISSUE THREAD

**Issue by ghost** [gr8pefish/IronBackpacks#231]
Hello, my problem is I glitched a backpack into another backpack and I can't take out that backpack.
It happened when I opened the backpack and pressed 9 (in the 9th slot I have another backpack). But when I tried to repeat, it doesn't glitched.
I can get back my items using NBT Explorer. I think you should create a config what can enable moving the backpack when a backpack GUI is open.

- IronBackpacks: 3.0.4
- Minecraft: 1.12.2
- Forge: 14.23.1.2601

Sorry for bad English, I'm hungarian.

**Comment by TehNut** [comment]
Update
