### ISSUE TITLE
[1.10.2] Dupe Glitch with a Nested Backpack

### ISSUE THREAD

**Issue by MainFreak** [gr8pefish/IronBackpacks#232]
#### Issue Description:
A duping issue caused by opening a "nested" backpack and throwing away the "nest" backpack while interacting inside the nested one. 
![javaw_2018-03-29_04-00-55](https://user-images.githubusercontent.com/20734190/38066468-662f47b2-3308-11e8-90cb-3d0e64e33cd6.png)
![javaw_2018-03-29_04-01-37](https://user-images.githubusercontent.com/20734190/38066484-711a8cd6-3308-11e8-8c2b-7f24415a6ad8.png)

#### What happens:
You can freely remove all items in the UI of the backpack that is inside of the one on the ground.

#### What you expected to happen:
Not being able to throw the nest backpack away

#### Steps to reproduce (important):

1. Add an (advanced) Nesting Upgrade to your backpack
2. Put items inside of a second backpack
3. Put the second backpack inside of the upgraded backpack
4. Open the nested backpack via right click
5. Throw away the nest backpack from your hotbar
6. Take out the items and pick the backpack back up afterwards.

#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: IronBackpacks-1.10.2-2.2.33
- Minecraft: 1.10.2
- Forge: 12.18.3.2511
- Other Conflicting Mods (may be irrelevant to your issue): none I guess.

**Comment by gr8pefish** [comment]
Thank you for the detailed report, but I'm no longer supporting 1.10 for anything other than critical bugfixes. I would love to fix everything, but have to prioritize 1.12 with my severely limited time.

**Comment by MainFreak** [comment]
Yeah this is understandable. Still thank you for taking a look at it. Maybe you also should check if that issue is still present in 1.12? If you don't have time I can try replicating it on the newest version myself.

**Comment by TehNut** [comment]
Nested backpacks don't exist in 1.12 currently.

**Comment by MainFreak** [comment]
Ah alright. Sorry for bothering once again.

**Comment by gr8pefish** [comment]
No worries, thanks for the assistance.
