### ISSUE TITLE
Scrolling up isn't shifting items properly with mousetweaks in backpacks

### ISSUE THREAD

**Issue by Xetaxheb** [gr8pefish/IronBackpacks#233]
#### Issue Description:
Scrolling up isn't shifting items properly with mousetweaks in backpacks, yet scrolling down works fine.

Maybe related to #220 ? Fps drops to about 30.

#### What happens:
I'm in singleplayer on enigmatica 2 expert modpack.

With mousetweaks set to "up push, down pull", scrolling down on a stack in the inventory or backpack "pulls" items from the other as expected. Scrolling up on a stack in the inventory "pushes" items as expected. Scrolling up on a stack in the backpack has serious issues and only sporadically works. This bug only takes place in an ironbackpack gui.

#### What you expected to happen:

Things to transfer smoothly.

#### Steps to reproduce (important):

1. Get diamond backpack and a stack of chests.
2. Put half a stack of chests in backpack.
3. Scroll up on stack of chests in backpack.
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.12.2-3.0.5-6
- Minecraft: 1.12.2
- Forge: 14.23.2.2645
- Other Conflicting Mods (may be irrelevant to your issue): Mousetweaks 2.8

**Comment by TehNut** [comment]
We have no code for MouseTweaks. This should not be on our end.
