### ISSUE TITLE
Items disappearing from backpack

### ISSUE THREAD

**Issue by ginkoopl** [gr8pefish/IronBackpacks#236]
#### Issue Description:

Items disappear from the backpack after the sevtech modpack updated (iron backpacks updated to latest version). 

#### What happens:

Sometimes when I put items into backpack and later open it, they disappear, not all of them, just the items that I put there at the time. They never disappear instantly, I open backpack right after and they're always there but after some time passes... they're gone.

#### What you expected to happen:

I expect items to stay in the backpack.

#### Steps to reproduce (important):

I don't know how to reproduce it, sometimes it happens and other times it's fine.

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.12.2-3.0.7-10
- Minecraft: 1.12.2 SevTech: Ages modpack
- Forge: 14.23.3.2679

**Comment by justinrusso** [comment]
Appears this has been reported on the sevtech issue tracker as well: https://github.com/DarkPacks/SevTech-Ages/issues/2402

I was not able to reproduce it with the steps the poster gave though.

**Comment by ginkoopl** [comment]
I'll keep an eye on that I guess, though an older version of Iron Backpacks works fine.

**Comment by Jandakast** [comment]
Just an update from the SevTech perspective. I was able to work around this issue by adding the ironbackpacks:backpack to the blacklist. Weird that only the keybind to open the backpack would allow you to shift click the bag into itself.

**Comment by TehNut** [comment]
When opened normally, the container knows which hotbar slot the backpack is in. When opened via the keybind, I assume @gr8pefish overlooked that and is not passing the slot of the opened bag.

**Comment by gr8pefish** [comment]
Yup, I assume that is the case as well.

**Comment by redawgts** [comment]
I'd like to report that I've had the same problem in the FTB Continuum pack. I'll note that I only access the backpack through the hotkey and I'm not sure if it's relevant or just a coincidence but the items that disappeared were all on the lowest bar of the backpack.

IronBackpacks: 1.12.2-3.0.7-10
Forge: 14.23.3.2689

**Comment by ginkoopl** [comment]
Are you sure you never put the backpack inside of itself? That seemed to be what caused the issue in sevtech.

> Jandakast commented 4 days ago
> I added the backpack to the blacklist and it fixes the ability to put the backpacks inside of themselves or other iron backpacks bags. I will keep an eye on this to make sure it stays fixed as we update further.

**Comment by gr8pefish** [comment]
With TehNut's recent [commit](https://github.com/gr8pefish/IronBackpacks/commit/de56cdc318621f728404bad6db220d5da9ab7ddc) blocking interactions with the keybind I believe this issue should be okay now.

**Comment by gr8pefish** [comment]
Should be good, feel free to reopen this issue if you notice it still occurring after updating.
