### ISSUE TITLE
Crash when using with Roboticraft

### ISSUE THREAD

**Issue by DomAmato** [gr8pefish/IronBackpacks#238]
Note: Delete the following 2 lines when you submit the issue. 

#### Issue Description:
Crash on startup when loading with roboticraft
https://gist.github.com/vrork/c52f4e128eae3ab91a81a5369b917971

So as a little explanation my mod enumerates all the blocks/items in the game so that they can be referenced by a python api. It does this as the last step of the registration process and tries to use the display name of the item stack and then its resource name. 

#### What happens:
The server crashes on initialization

#### What you expected to happen:
The server to start

#### Steps to reproduce (important):

1. Have roboticraft and ironbackpacks
2. start server
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.12.2-3.0.8-12
- Minecraft: 1.12.2
- Forge: 14.23.3.2702 
- Other Conflicting Mods (may be irrelevant to your issue): roboticraft

**Comment by TehNut** [comment]
#237
