### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by forestbat** [gr8pefish/IronBackpacks#240]
Note: Delete the following 2 lines when you submit the issue. 
* If this bug occurs in a modpack, please try first reporting it to the modpack author. Barring that, please narrow down exactly what other mod(s) are responsible for the issue. 
* If this is a feature request, this template does not apply to you. Just delete everything and write what you need.

#### Issue Description:
After add roboticraft to the modpack，it crashed during loading。

#### Steps to reproduce (important):

1. https://paste.ubuntu.com/p/xDNc6BHj69/
2. If remove roboticraft，there is no error。
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 3.0.8-12
- Minecraft: 1.12.2
- Forge: 2703
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by TehNut** [comment]
#237
