### ISSUE TITLE
Dupe Bug & Lost Backpack

### ISSUE THREAD

**Issue by Imrtltrtl** [gr8pefish/IronBackpacks#241]
You can shift click your backpack into itself when opened with the hotkey, possibly losing your bag forever. You can also just move the bag in any way, even putting it back down where it was to 'reset' your bag to whatever it was before you opened it, possibly duplicating the items inside or destroying the ones you put into it before you close it. You can also lose your items this way, if you put items in and accidentally move the bag via misclick or shift click, you 'reset' the bag and anything new you put into it will be destroyed.

#### Steps to reproduce (important):

1. Open bag with hotkey.
2. Pick up bag or shift click bag
3. Put it back down or put it into itself to lose it forever lol
4. Re-open the bag to see that whatever was in it before you opened it the previous time, is in there again.

____
#### Affected Versions (Do *not* use "latest"): IronBackpacks-1.12.2-3.0.7-10

- IronBackpacks: IronBackpacks-1.12.2-3.0.7-10
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2676

**Comment by TehNut** [comment]
#234
