### ISSUE TITLE
Conflict with Roboticraft and at least 2 backpack mods.

### ISSUE THREAD

**Issue by AlphaSparqy** [gr8pefish/IronBackpacks#242]
#### Issue Description:
The issue isn't with your mod, it runs fine with 359 other mods I'm playing around with.

The issue is with the mod Roboticraft (https://minecraft.curseforge.com/projects/roboticraft) and IronBackpacks, but it's getting a nearly identical NPE with WearableBackpacks, as well.

#### What happens:
Modified instance to just 3 mods, for this crash-report

https://pastebin.com/1iTYSp3d

java.lang.NullPointerException: Initializing game
    at gr8pefish.ironbackpacks.item.ItemUpgrade.func_77667_c(ItemUpgrade.java:36)

#### What you expected to happen:
IronBackpacks code causing NPE, only with Roboticraft installed.

    @Override
    public String getUnlocalizedName(ItemStack stack) {
        BackpackUpgrade backpackUpgrade = getUpgrade(stack);
        if (backpackUpgrade.isNull())
            return super.getUnlocalizedName(stack);

        return "upgrade.ironbackpacks." + backpackUpgrade.getIdentifier().getResourcePath();
    }

WearableBackpacks code causing NPE, only with Roboticraft Installed.

	@Override
	public String getUnlocalizedName() {
		// Just use the item's unlocalized name for this block.
		return MiscUtils.getItemFromBlock(this).getUnlocalizedName();
}

It would seem, that the .getUnlocalizedNamed() is the commonality?

#### Affected Versions (Do *not* use "latest"):
- MultiMC 5: 0.6.20-1222
- Forge: 14.23.4.2703
- Minecraft: 1.12.2
- IronBackpacks: 1.12.2-3.0.8-12
- Rabbit-GUI (required for Roboticraft): 1.12.2
- Roboticraft: 0.10.3

Thank you!

I have also posted this on the WearableBackpacks Git issues, where the Roboticraft author had started the issue.

https://github.com/copygirl/WearableBackpacks/issues/80

**Comment by TehNut** [comment]
#237 he is calling that shit way too early.

**Comment by AlphaSparqy** [comment]
Ya, I should have searched deeper before posting, only after I saw the previous ones.

My bad.
