### ISSUE TITLE
can't apply any upgrade

### ISSUE THREAD

**Issue by jotac0** [gr8pefish/IronBackpacks#249]
Note: Delete the following 2 lines when you submit the issue. 
#### Issue Description:
when i craft a backpack with an upgrade, i can't apply it, for all backpacks

#### What happens:
can't craft the backpack with the upgrade, even if it is empty

#### What you expected to happen:
the upgrade to be applied to the backpack
or have a description on how to apply upgrades, am i missing something?

#### Steps to reproduce (important):

1. place a backpack in the crafting with an upgrade, nothing happens!

...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: IronBackpacks-1.12.2-3.0.8-12
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2725
- Other Conflicting Mods (may be irrelevant to your issue):well ..

**Comment by TehNut** [comment]
Anvil
