### ISSUE TITLE
Opening backpack on world load.

### ISSUE THREAD

**Issue by ReverentMachine** [gr8pefish/IronBackpacks#25]
Left the backpack on my character when I logged out of singleplayer world, closed the game.
Logged back in and attempted to open the backpack, crashed the game and was loaded to the server page with a "Critical Error" message.
Repeated error until I unequipped and re-equipped backpack.

Minecraft Version: 1.7.10
Iron Backpacks Version: 1.1.2
Forge Version: 10.13.4.1558
No conflicting mods.

**Comment by MaxWason** [comment]
Please update to a newer version and let me know if this happens again. Version 1.1.2 is really old at this point.

**Comment by gr8pefish** [comment]
Please update to a newer version and let me know if this happens again. Version 1.1.2 is really old at this point.

**Comment by gr8pefish** [comment]
If it happens again create a new bug report please. Next time with the error message (or at least a very detailed account of what happened), as I doubt I could replicate the issue without it.
