### ISSUE TITLE
Unlocalized item name

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [gr8pefish/IronBackpacks#250]
#### Issue Description:
The back pack's localized name isn't shown

#### What happens:
https://cdn.discordapp.com/attachments/380746423974756352/477135997780361217/unknown.png

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 3.0.8-12
- Minecraft: 1.12.2
- Forge: 2739+

**Comment by gr8pefish** [comment]
Does this always happen, or does it only occur with Project E interactions?

What are the steps to reproduce this issue?

Thanks.

P.S. I see you're using Discord. I've got a [channel](https://discord.gg/2gkhaFu) myself if you want to come chat more.

**Comment by TehNut** [comment]
They are displaying an invalid backpack

**Comment by Pythonic-Rainbow** [comment]
Here is my theory:

The bug originated from ProjectE scanning ability
Because Backpacks are crafted with vanilla materials that have EMC values
so ProjectE thinks ['Hm, this means output should have EMC value too, right?"](https://cdn.discordapp.com/attachments/380746423974756352/477142127462055947/unknown.png)

Due to the fact that backpacks share the same item id
The trouble begins:

If you transmute a backpack with items inside
you lose these items
and you can't even get a functioning backpack back again
you get purple bugged texture thingie
if you really want your backpack back
you just burn the bugged item for EMC again
and get backpack components
and craft backpack again
but items that were inside the initial transmuted backpack are lost forever

**Comment by TehNut** [comment]
The only thing I can really say is to blacklist the backpack in the EMC table

**Comment by sinkillerj** [comment]
Explanation is posted in sinkillerj/ProjectE#1734. This is not a issue with Iron Backpacks.
