### ISSUE TITLE
major glitch with ironbackpacks in selfmade 1.7.10 modpack

### ISSUE THREAD

**Issue by jongamer2006** [gr8pefish/IronBackpacks#253]
Note: Delete the following 2 lines when you submit the issue. 

#### Steps to reproduce (important):i dont know what went wrong when i left the world evrything was normal

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):1.7.10

- IronBackpacks: 
- Minecraft: 
- Forge: 
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by jongamer2006** [comment]
the rest of the crash report 8/29/18 9:59 PM
Description: Ticking block entity

java.lang.ClassCastException: main.ironbackpacks.entity.EntityBackpack cannot be cast to net.minecraft.entity.EntityLivingBase
	at com.hbm.tileentity.machine.TileEntityReactorMultiblock.func_145845_h(TileEntityReactorMultiblock.java:516)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.tileentity.machine.TileEntityReactorMultiblock.func_145845_h(TileEntityReactorMultiblock.java:516)
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Block entity being ticked --
Details:
	Name: tileentity_reactor_multiblock // com.hbm.tileentity.machine.TileEntityReactorMultiblock
	Block type: ID #1840 (tile.reactor_computer // com.hbm.blocks.machine.ReactorCore)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-251,51,140), Chunk: (at 5,3,12 in -16,8; contains blocks -256,0,128 to -241,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #1840 (tile.reactor_computer // com.hbm.blocks.machine.ReactorCore)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['jongamer2006'/206, l='New World', x=-255.85, y=50.00, z=141.90]]
	Chunk stats: ServerChunkCache: 995 Drop: 0
	Level seed: -4939957242182144297
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-873,64,847), Chunk: (at 7,4,15 in -55,52; contains blocks -880,0,832 to -865,255,847), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 2224985 game time, 2241674 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 101184 (now: false), thunder time: 94724 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 834975944 bytes (796 MB) / 1375731712 bytes (1312 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 97
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 113 mods loaded, 101 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJAAAA	<CJB ASM>{000} [<CJB ASM Data Initialization>] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	debug{1.0} [debug] (Dense-Ores-Mod-1.7.10.jar) 
	UCHIJAAAA	imsm{1.7.10} [Instant Massive Structures Mod] ([1.7.10]InstantMassiveStructuresMod2.jar) 
	UCHIJAAAA	uncraftingTable{1.4.7} [Uncrafting Table] ([1.7.10]UncraftingTable-1.4.7.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.18} [BuildCraft] (_buildcraft-mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.18} [BC Transport] (_buildcraft-mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.18} [BC Silicon] (_buildcraft-mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.18} [BC Energy] (_buildcraft-mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.18} [BC Factory] (_buildcraft-mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.18} [BC Builders] (_buildcraft-mod-1.7.10.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.18} [BC Robotics] (_buildcraft-mod-1.7.10.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) 
	UCHIJAAAA	FLabsBF{4.3} [Better Furnaces] (Better-Furnaces-Mod-1.7.10.jar) 
	UCHIJAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-Mod-1.7.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
	UCHIJAAAA	buffedtools{1.1.1710.1} [Buffed Tools] (BuffedTools-1.1.1710.7.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	CJBAPI{1.7.10.1} [CJB API] (CJB-API-1.7.10.jar) 
	UCHIJAAAA	CJB|XRay{1.7.10.0} [CJB X-Ray] (CJB-X-Ray-Mod-1.7.10.jar) 
	UCHIJAAAA	comp101{0.1.1} [Companion mod] (Companions-Mod-1.7.10.jar) 
	UCHIJAAAA	CraftableAnimals{2.4.3.0} [Craftable Animals] (Craftable-Animals-Mod-1.7.10.jar) 
	UCHIJAAAA	Eggs{1.0.0} [Eggs] (Craftable-Spawn-Eggs-Mod-1.7.10.jar) 
	UCHIJAAAA	lootablebodies{1.3.7} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.7.10-backport_1.3.7.jar) 
	UCHIJAAAA	D3Core{1.0.0.6} [D3Core] (D3Core-1.7.10-1.0.0.6.jar) 
	UCHIJAAAA	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	ewysworkshop{Ewy's Workshop-1.7.10-1.1.2} [Ewy's Workshop] (Ewy's Workshop-1.1.4.jar) 
	UCHIJAAAA	exnihilo{1.38-53} [Ex Nihilo] (Ex-Nihilo-1.38-53.jar) 
	UCHIJAAAA	excompressum{1.1.143} [Ex Compressum] (excompressum-mc1.7.10-1.1.143.jar) 
	UCHIJAAAA	golems{1.20} [Extra Golems] (Extra-Golems[1.7.10]-1.20.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) 
	UCHIJAAAA	ezstorage{1.1.0} [EZ Storage] (EZStorage-Mod-1.7.10.jar) 
	UCHIJAAAA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (Cobalt-X08)} [Hbm's Nuclear Tech] (hbm1.0.27_BETAX08.jar) 
	UCHIJAAAA	inventorytweaks{1.57-116} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) 
	UCHIJAAAA	ironbackpacks{1.7.10-1.2.20} [Iron Backpacks] (Iron-Backpacks-Mod-1.7.10.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10 (1).jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.7.10-1.9.jar) 
	UCHIJAAAA	morefuelsmod-1.7.10{1.3.1} [More Fuels Mod] (More-Fuels-Mod-1.7.10.jar) 
	UCHIJAAAA	me{1.3.2.1} [More Enchantments] (MoreEnchantments-1.7.10-1.3.2.1.jar) 
	UCHIJAAAA	AencEx{0.0.1} [AencEx] (MoreEnchantments-1.7.10-1.3.2.1.jar) 
	UCHIJAAAA	Morph{0.9.2} [Morph] (Morphing-Mod-1.7.10.jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10.jar) 
	UCHIJAAAA	rivalrebels{1.7.10Y} [Rival Rebels] (Rival-Rebels-Mod-Yes-Oceans-1.7.10.jar) 
	UCHIJAAAA	Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
	UCHIJAAAA	AS_Ruins{15.4} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (Secret-Rooms-Mod-1.7.10.jar) 
	UCHIJAAAA	cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	ShowDurability2{1.3.0} [ShowDurability2] (Show-Durability-2-Mod-1.7.10.jar) 
	UCHIJAAAA	spawnercraft{1.7.10-2.2.1} [SpawnerCraft] (SpawnerCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	terracart{1.7.10-2} [TerraCart] (Terracart-Mod-1.7.10.jar) 
	UCHIJAAAA	ThermalSmeltery{1.0} [Thermal Smeltery] (Thermal-Smeltery-Mod-1.7.10.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJAAAA	TMechworks{0.2.15.106} [Tinkers' Mechworks] (Tinkers-Mechworks-Mod-1.7.10.jar) 
	UCHIJAAAA	tinkersdefense{1.3.7} [Tinkers' Defense] (tinkersdefense-1.3.7.jar) 
	UCHIJAAAA	TooMuchTNT{2.9} [TooMuchTNT] (Too-Much-TNT-Mod-1.7.10 (1).jar) 
	UCHIJAAAA	torchLevers{1.4} [Torch Levers] (Torch-Levers-Mod-1.7.10.jar) 
	UCHIJAAAA	uncrafted{2.2.0} [Uncrafted Mod] (Uncrafted+1.7.10+(v.2.2.0) (1).jar) 
	UCHIJAAAA	waystones{1.0.12} [Waystones] (Waystones-Mod-1.7.10.jar) 
	UCHIJAAAA	weaponcaseloot{1.2.12} [WeaponCaseLoot] (weaponcaseloot-1.2.12.jar) 
	UCHIJAAAA	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	denseores{1.0} [Dense Ores] (Dense-Ores-Mod-1.7.10.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: found misbehaving transformers: invtweaks.forge.asm.ContainerTransformer(invtweaks.forge.asm.ContainerTransformer@7dc09694) crashed with java.lang.NullPointerException(null),me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@96beec) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@799bfc5c) returned non-null result: 0
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	Mantle Environment: Environment healthy.
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['jongamer2006'/206, l='New World', x=-255.85, y=50.00, z=141.90]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by TehNut** [comment]
This is an error in whatever `hbm` is.

**Comment by jongamer2006** [comment]
thx dude
