### ISSUE TITLE
ProjectE missingtexture/entry error

### ISSUE THREAD

**Issue by Trisscar05** [gr8pefish/IronBackpacks#256]
#### Issue Description:
Dropping any backpack from this mod into the transmutation table of ProjectE causes the table's entry (of the dropped-in item) to combine with any other entries of the backpacks of this mod, produces a null texture, sets the value to 4k or so (gold backpack assigned value), and changes the name to a string of def code. Taking the null textured backpack out of the table results in a working backpack with one single slot and the same name and texture issue.

Removing the EMC value with commands does not appear to work, that may be an issue on ProjectE's end however.

#### Steps to reproduce (important):

1. Drop any of the four backpacks into an ProjectE Transmutation Tablet's (or Table's) UI
2. Do so again for another of the backpacks
3. Witness the glorious purple and black squares, maybe take it out and admire it's single inventory slot
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 3.0.8-12
- Minecraft: 1.12..2
- Forge: 14.23.5.2806
- Other Conflicting Mods (may be irrelevant to your issue): ProjectE - PE1.3.2h

**Comment by TehNut** [comment]
#250
