### ISSUE TITLE
Basic Filter Upgrade not working [1.2.3]

### ISSUE THREAD

**Issue by dirtyfargo** [gr8pefish/IronBackpacks#26]
Version: 1.2.3
Forge: 10.13.4.1566
Basic Filter Upgrade not automatically collecting items into backpack as it should. Reverting to 1.2.1 fixes the issue =)

**Comment by gr8pefish** [comment]
Gah, I swear I'm better than this! It's been a long week. At least you can't complain I'm an inactive dev :P

Fixed for the next version. Thanks for the bug reports.

**Comment by dirtyfargo** [comment]
Haha no worries at all, thanks for fixing everything so fast :P

**Comment by gr8pefish** [comment]
1.2.4  is on curseforge waiting for approval. Edit: It's approved.

Glad you enjoy it! And if you have any suggestions/balance issues/etc. please feel free to let me know. I don't really have time to play (and mod) Minecraft right now, so my concepts of usability and balance are probably a little bit off.

**Comment by dirtyfargo** [comment]
I hear you, I play when I can and generally progress a lot slower than most due to the limited time I have to actually grind it out! So there's still a lot in Iron Backpacks that I haven't even gotten to playing with yet, but Ill be sure to let you know if I think of anything, and awesome loading up 1.2.4 now :)

**Comment by gr8pefish** [comment]
Alright cool, good feedback is always greatly appreciated :)
