### ISSUE TITLE
i can't wear backpacks

### ISSUE THREAD

**Issue by Scarterrr** [gr8pefish/IronBackpacks#260]
#### Issue Description:
in game it says to edit the config file to allow wearable backpacks but there is nothing in the config file

#### Steps to reproduce (important):

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 1.12.2-3.0.8-12
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.5.2836
- Other Conflicting Mods (may be irrelevant to your issue):

**Comment by TehNut** [comment]
Not implemented in 1.12
