### ISSUE TITLE
Tooltip Client Crash [1.2.4]

### ISSUE THREAD

**Issue by dirtyfargo** [gr8pefish/IronBackpacks#27]
Description: When holding shift while hovering your mouse over backpack upgrades in NEI to see more info, it displays as 'unknown', as can be seen in the Gyazo .gif linked below. When I hold shift and hover over one of the  backpack upgrades while inside the NEI recipe display for it, I receive the client crash linked below.
(Sorry for having another bug again lol)
Example Gif: https://gyazo.com/f3da4c2273ec9b2f6a8860cc2d41345e
Crash Report: https://gist.github.com/2e05f9929b3f41f50d51

**Comment by TehNut** [comment]
@gr8pefish You imported the wrong `Arrays` class. You want [`java.util.Arrays`](https://github.com/gr8pefish/IronBackpacks/blob/1.8/src/main/java/main/ironbackpacks/items/upgrades/ItemUpgradeBase.java#L13), not [`scala.actors.threadpool.Arrays`](https://github.com/gr8pefish/IronBackpacks/blob/devSweden/src/main/java/main/ironbackpacks/items/upgrades/ItemUpgradeBase.java#L10)

**Comment by TehNut** [comment]
Fixed in 1.2.5

**Comment by gr8pefish** [comment]
Amateur mistakes for days! Ugh :/
