### ISSUE TITLE
Crafting Upgrade making slabs [1.7.10-26]

### ISSUE THREAD

**Issue by dirtyfargo** [gr8pefish/IronBackpacks#28]
Version: 1.7.10-26
Forge Version: 10.13.4.1566
Description: Crafting upgrade when used with cobblestone, automatically crafts into slabs instead of the compressed cobblestone from Extra Utilities that I would prefer.  I understand why this is happening, but I think it would be nice to perhaps have an Advanced Crafting Upgrade that allows more control over which recipe you choose to be crafted maybe? Just a thought anyways, not sure if this is a real issue or working as intended. :)

**Comment by gr8pefish** [comment]
I'll look into this when I have time, I'm on vacation at the moment and am unable to check it out at the moment.

**Comment by dirtyfargo** [comment]
No worries, have a good vacation! :)

**Comment by gr8pefish** [comment]
So to clarify: You are using the (normal, unspecified, _not_ the small or tiny) crafting upgrade with cobblestone specified and you are getting cobblestone slabs as the output? Because, if so, that is not working as intended, it should fill the crafting grid, so it should give you compressed cobble.

**Comment by dirtyfargo** [comment]
Yes exactly, I was using the normal Crafting upgrade, not the new small or tiny variants. And yes its making slabs and not compressed cobble, so I guess its an issue!

**Comment by gr8pefish** [comment]
Fixed now, thanks for the report. I just forgot to square 1 number so it was placing the items in the crafting grid in a row, not a square, and so it was an easy fix.

I do want to do a "Fancy Crafting Upgrade" at some point, with the ability to do some fancy automatic crafting (probably a button under each slot (like the fancy filter) which allows you to choose the size of each item to be crafted (so if it acts like the tiny, small, or normal crafting upgrade), _maybe_ introduce a custom ghost crafting grid where you specify the recipe, maybe something else), but that isn't my biggest priority right now.

**Comment by gr8pefish** [comment]
Curseforge is taking a while to accept the file, so [here](https://github.com/gr8pefish/IronBackpacks/releases) is where you can get the file in the meantime.

**Comment by dirtyfargo** [comment]
Awesome thanks for the fix :) Fancy crafting upgrade sounds like it would be neat as well.
