### ISSUE TITLE
[1.8.8] Crash on load with recent Forge build

### ISSUE THREAD

**Issue by wlhlm** [gr8pefish/IronBackpacks#29]
IronBackpacks fails to load on recent Forge 1.8.8 builds. I guess this is due to the new registry fixes (for example MinecraftForge/MinecraftForge@97ef6a5d1fb7f9abd4052ab449b089533a2c7938).

Relevant line from the log:

```
java.lang.ClassCastException: java.lang.String cannot be cast to net.minecraft.util.ResourceLocation
```

[Crashlog](https://paste.ee/p/fvWsK)

IronBackpacks: 1.8-1.0.6
Forge: 11.15.0.1608-1.8.8

**Comment by TehNut** [comment]
Hrm... This might remove compatibility with `1.8`... I guess that's fine?

**Comment by gr8pefish** [comment]
Do whatever you think is best, I'm not sure.

**Comment by TehNut** [comment]
I'm testing a fix that might allow both

**Comment by wlhlm** [comment]
Thanks for the quick fix! It starts up now without crashing.

One thing I have noticed though from quickly trying it out in creative, is that I'm not able to equip a backpack with 'B' as is stated in the MCF post (I couldn't find any other shortcut that would equip it for that matter...).

**Comment by gr8pefish** [comment]
Yes, that is because it isn't implemented in the 1.8 version. I only have time to work on 1 version (1.7) and TehNut is busy as well, so the 1.8 version will be less feature rich than the 1.7 one will. I should make that more clear in the MCF posting though.

**Comment by wlhlm** [comment]
No pressure. I can open a separate issue, if you think it's appropriate.

The current 1.8.8 modding situation is pretty dire anyways...

**Comment by TehNut** [comment]
> I can open a separate issue, if you think it's appropriate.

No, I'm working on it right now. Just have other projects that need my attention a bit more than that.

> The current 1.8.8 modding situation is pretty dire anyways...

Not really...
