### ISSUE TITLE
Filter upgrade doesn't work with durability-using items.

### ISSUE THREAD

**Issue by Adamantium9001** [gr8pefish/IronBackpacks#3]
Basically: If you put an item with durability in the filter upgrade, the backpack will only pick up more copies of that item if they have the same durability remaining as the one in the filter upgrade.

Precise steps to reproduce: get a backpack with a filter upgrade. Put a brand-new diamond shovel in one of its filter slots. Get a second diamond shovel, this one slightly damaged, and throw it on the ground. Then walk over it to pick it up. Expected behaviour: the damaged shovel goes into the backpack. Observed behaviour: the shovel goes into your normal inventory.

**Comment by gr8pefish** [comment]
Thanks for the nicely presented info.

My plan is to add in a fuzzy filter that ignores damage value, and I will rename the existing filter to a basic filter so it is more clear that it doesn't take damage values into.
