### ISSUE TITLE
Crafting Upgrade Lag - copy from MCF post

### ISSUE THREAD

**Issue by gr8pefish** [gr8pefish/IronBackpacks#31]
> I have an issue with iron backpacks and lag/time out. I have a diamon backpack with crafting upgrade and basic filter upgrade. I have it set for cobble and coal to filter into bag. Cobble/coal also gets compressed up to double compressed cobble. If i keep mining until my inventory is full (terrashatter) When my inventory reaches full the server tps drops and we experience server lag. I can reproduce this quite regularly. 1.7.10 version

**Comment by TehNut** [comment]
Check if the inventories are full before doing anything. That _should_ solve this. Not sure where the logic is, but I assume it doesn't check that.

**Comment by gr8pefish** [comment]
Should be fixed, but as my laptop can't even run minecraft at all right now (1 fps is always laggy), I can't check to be sure.
