### ISSUE TITLE
Incorrect use of doIt

### ISSUE THREAD

**Issue by yrsegal** [gr8pefish/IronBackpacks#33]
https://github.com/gr8pefish/IronBackpacks/blob/d159935103ad524a7f1c45dfad272076a72d3efb/src/main/java/main/ironbackpacks/items/backpacks/ItemBackpack.java#L217-L242

If `doIt` is true, mana should be consumed. This will produce unexpected behavior. You should replace those lines with:

https://gist.github.com/yrsegal/d54f6cbb1ad7d929e96c

(this isn't big enough for a PR)

**Comment by gr8pefish** [comment]
Check the [botania issue](https://github.com/Vazkii/Botania/issues/1629), I explained that it was correct and it was the return value that caused the trouble.
