### ISSUE TITLE
Equipped backpack deleting items

### ISSUE THREAD

**Issue by Nezraddin** [gr8pefish/IronBackpacks#36]
Hello.

I'm using the latest version of the mod (updated it myself in the modpack I'm playing) and similar to the closed issue #10 I have problem that an backpack that I have equipped seems to delete items.

I tried to reproduce it and it seems to "save" all items you put in before closing the game. (so the "quit" saves the items)
Every items you put into the backpack after starting the game again are in danger to be deleted.

I did quiet some testing about the "when" it disappears, since I first couldn't reproduce this "action" that needs to happen so all but the safe items disappear. What I found out:
- It happens when you "place" a chest.
- the items you put into the backpack once the chest is placed are safe for as long as you do not place another chest.
- as mentioned aboth: all items you carry in the backpack when logging out seems to be safe from this bug, but while playing any chest you place seems to delete any items you put in after logging back in.
- Similar to the issue #10 the bug is fixed by taking the backpack off, opening it from the hotbar and reequipping it. So opening it once from the hotbar seems to make it bug-proof at least until you close the game and start it again with it still equipped.

**Comment by gr8pefish** [comment]
Thanks for the detailed report, this is next on my list to fix.

**Comment by gr8pefish** [comment]
I cannot duplicate this. 

Furthermore, your bug report is quite confusing. You mentions chests, but I have very little interaction with chests, my mod is about backpacks.

Can you describe the _exact steps_ needed to duplicate this bug? That would help immensely. Barring that, I need a much more clear description.
