### ISSUE TITLE
Equipped backpack never goes in the grave.

### ISSUE THREAD

**Issue by kane-thornwyrd** [gr8pefish/IronBackpacks#40]
When you use a grave mod, like Twograve or Gravestones or Openblock, if your backpack is equipped at death he'll simply drop beside.

**Comment by gr8pefish** [comment]
Really?

I haven't tested it with Twograve or Gravestones, but Open Blocks graves' work just fine for me. Can you do a little more and make sure you can verify/duplicate this please (with the Open Blocks one at least)? 

Thanks.

**Comment by kane-thornwyrd** [comment]
Sorry, I re-tested every grave mod I knew of, you we're right about OpenBlocks:

[About TestBed](http://minecraft.curseforge.com/projects/testbed)

## GraveStone

### Env
- Modpack: Testbed
- Mods added:
  - Iron Backpacks 1.2.12
  - GraveStone 2.16.0

### Scenarios/Results
- `/kill` with backpack equipped (B key)
  - Backpack dropped beside.
- `/kill` with backpack in inventory
  - Backpack in the grave

## BaM's Grave

### Env
- Modpack: Testbed
- Mods added:
  - Iron Backpacks 1.2.12
  - BaM's Grave 1.4.2_01

### Scenarios/Results
- `/kill` with backpack equipped (B key)
  - no grave, backpack beside.
- `/kill` with backpack in inventory
  - no grave, backpack beside.

## GraveStones -Die Classy

### Env
- Modpack: Testbed
- Mods added:
  - Iron Backpacks 1.2.12
  - GraveStones -Die Classy 1.7.10-3

### Scenarios/Results
- `/kill` with backpack equipped (B key)
  - Backpack dropped beside.
- `/kill` with backpack in inventory
  - Backpack in the grave

## TwoGraves

### Env
- Modpack: Testbed
- Mods added:
  - Iron Backpacks 1.2.12
  - TwoGraves "Latest Release" (mmm lol)

### Scenarios/Results
- `/kill` with backpack equipped (B key)
  - Backpack dropped beside.
- `/kill` with backpack in inventory
  - Backpack in the grave

## OpenBlocks

### Env
- Modpack: Testbed
- Mods added:
  - Iron Backpacks 1.2.12
  - OpenBlocks 1.5
  - OpenModsLib 0.9

### Scenarios/Results
- `/kill` with backpack equipped (B key)
  - Backpack in the grave
- `/kill` with backpack in inventory
  - Backpack in the grave

**Comment by gr8pefish** [comment]
Thanks for this level of detail, it makes my life _a lot_ easier.

Here's what I will do. ~~I'll attempt to put the equipped backpack in the player's inventory right as they die, meaning the graves mods should handle that nicely (I'm guessing open blocks operates a tick or two later and picks up any items that drop, hence why it works well). But if the player's inventory is already full I will just have to drop it on the ground, there is not really an alternative (except I might do a GraveStone compat as it is decently popular).~~ Edit: It looks like I do this already actually, the other graves mods must be doing something odd, I will have to look into how they handle it specifically.

Note that if you do have the "eternity upgrade" (i.e. keep it through death), you should respawn with the equipped pack just fine.

I'll leave this issue up until I have implemented the above.

**Comment by kane-thornwyrd** [comment]
Yes, I know about the eternity upgrade, I love it ! in fact, the only thing I'm not totally fond of about your mod are the icons, but ya, that's fine !

**Comment by gr8pefish** [comment]
If you are a texturing artist I am more than willing to accept help, I know they aren't that great :/ I'm a decent "normal" artist, but a bad digital one.

I'll test with GraveStones and try to get that to work, and as long as it works with that mod and OpenBlocks (the two most popular gravestones) I am going to call this issue good.

And thank you!!

**Comment by Crowfooted** [comment]
As far as I know, the solution of making backpacks enter the inventory upon death would only work if the player has empty slots in their inventory.
