### ISSUE TITLE
Graphics Overhaul

### ISSUE THREAD

**Issue by gr8pefish** [gr8pefish/IronBackpacks#44]
Okay, so the graphics on this mod are a bit lacking in some regards. Let's go through the list:
- _Models_:
  I'm actually semi-pleased with how the backpack model looks; it seems like it fits in Minecraft while still having some detail. Improvement could still be done of course though.
- _Backpack Items_:
  These items seems decent, they look pretty nice, but they are 32x32 variants, so they don't necessarily fit in well with everything else. The alternate ones (16x16) look bland and unsatisfying as well.
- _Upgrade Items_:
  These need the most work, they look gross, if I'm honest with myself. They should probably all be redone (but once a base is made for one the rest should go quicker).
- _Miscellaneous Items_:
  Items such as the nest and treated leather; these look okay, work could be done to them but they don't need it as much as, say, the upgrades do.
- _GUIS_:
  With the exception of some of the alternate GUIs, these look good, in my opinion, as they are very "vanilla." The clutter of the alternate GUI is the result of code more than art, so I will work on that.
- _Other_:
  I could use a logo and or cover picture as well, but that stuff is optional for sure.

Summoning @BBoldt :) If you have any questions/comments/concerns please don't hesitate to post them here. I love Unity, so I'm sure whatever you do will be fine if you end up doing anything :D

**Comment by gr8pefish** [comment]
No need to keep the issue; with the update on graphics all I really need now is a logo/cover picture/banner/etc.

**Comment by BBoldt** [comment]
@gr8pefish I'll make you one, give me a day or two.

**Comment by gr8pefish** [comment]
Thanks man, much appreciated! :)

**Comment by gr8pefish** [comment]
Hey, I know you're probably really busy, but if you don't mind I could use that banner/logo soon. I'm doing a bunch of documentation/updating curseforge page/etc. and it would be really nice to have that ready to go so I can get the layout down, and have it look nice for those who look at it for this new 1.10 beta.

If you are too busy, no worries; just let me know so I can either do it myself or ask someone else from unity if they could work on it. Thanks!
