### ISSUE TITLE
Dupebug

### ISSUE THREAD

**Issue by Makin91** [gr8pefish/IronBackpacks#45]
Running minecraft 1.8.9 
When ever i try to pickup amber from thaumcraft, with a iron backpack configured with a mod spesific filter, filtered to ambers. it picks up the ambers and creates BOP ambers inside the backpack and the thaumcraft ambers just go into my inventory.

**Comment by Makin91** [comment]
it actully duplicates everything i pickup.

**Comment by gr8pefish** [comment]
Yeah, sorry about that. I'm not going to fix that bug, as it is for TehNut's 1.8.9 port. I will make sure it doesn't occur in the 1.8.9 rewrite I am working on, as I should get that version out "relatively soon" (as soon as I can). You just caught me at a bad time, I am quite busy IRL right now and I don't have time to work on multiple branches, sorry. Rest assured that I will get that new 1.8 version out asap though.
