### ISSUE TITLE
Crash when equipping backpack

### ISSUE THREAD

**Issue by jrpoints** [gr8pefish/IronBackpacks#52]
I used V to put a gold backpack on my back with no issue, I then added nesting to it and put a iron bag inside. When I tried to wear it again I got a server crash with this report. Upon restart I was wearing the gold bag and it let me take it off again. So it mostly worked besides the crash part. 

[http://pastebin.com/ZWfvKzwW](url)

**Comment by gr8pefish** [comment]
Hmm, can you be more explicit on what exactly happened? I'm having trouble replicating it.

Also: Are you on a server, singleplayer, or LAN world?

**Comment by jrpoints** [comment]
I am playing on a server, I had just updated from 1.0.7 to 2.0.5. Made a gold backpack, and used V to try out the equip feature, with a empty gold bag it worked fine. I then upgraded it with nesting, and put a iron bag with basic filter in it, then I tried to equip it when I got that crash. 

After trying to replicate it I couldn't, I was able to equip and re-equip many times. I then started to spam V to equip un-equip fast and after a few it crashed again with the same error.So I don't know the exact cause of the crash, and I was not able to replicate at all in single player, so it seems to be server issue only.

I will test further when people aren't on the server to see if i can pinpoint a situation that duplicates the crash.

**Comment by gr8pefish** [comment]
Okay, sounds good.

I tried to spam 'v' to get the crash in my dev. environment and I couldn't. It could just be that it was the change from 1.0.7, as I did change _a lot_ between those two versions. I know the issue, you are right that it is definitely server specific.

If you could try to duplicate it again I would appreciate it. And if you are able to (or not), let me know, and I will see if I can fix it if it persists or close the issue if it doesn't. Without duplication I'm afraid I can't do much about it though.

**Comment by jrpoints** [comment]
I removed all mods and deleted configs folder to let it build a fresh one, I am on latest forge 1726.

I am able to get the crash with just ironbackpacks installed and nothing else. I have a gold bag with a basic nesting upgrade, iron bag with basic filter upgrade, I put iron bag inside the gold bag. and just start steadily equipping and unequipping and get the crash but it seems extremely random, sometimes on the first equip sometimes it take minutes, possibly loading terrain has a effect, could be a desync issue?

That's about all I can think do to remove variables, I know its probably something that cant be easily fixed, being its so random but here is the crash with just ironbackpacks if that might help.

[http://pastebin.com/cjJFrg9C](url)

**Comment by gr8pefish** [comment]
Thanks for the testing.

I am almost certain it is due to 1.8 being multi-threaded and I am trying to access something on both threads simultaneously. I'll have to figure this one out, but it is an intermittent bug and threads are not my area of expertise, so I can't promise a quick fix.
