### ISSUE TITLE
Void Filter doesn't work without Advanced Filter Upgrade also installed

### ISSUE THREAD

**Issue by CyborgShadow** [gr8pefish/IronBackpacks#53]
On our server with Iron Backpacks, I have a Diamond backpack with only a basic filter and void filter.

Sadly, the void filter doesn't work when told to delete things like cobblestone.

In testing, it appears this only works properly when an Advanced Filter Upgrade is also installed.

**Comment by gr8pefish** [comment]
1.7 or 1.8?

If 1.8: And it only works when it has an advanced filter on the backpack, or when the void setting is on a slot of the advanced filter?

**Comment by CyborgShadow** [comment]
1.7.10 Windows 7.

**Comment by gr8pefish** [comment]
Just checked, it's fixed on 1.10, so it is truly 1.7 specific. I'll fix it in the next week or so, focusing on 1.10 right now.

**Comment by gr8pefish** [comment]
Void filter seems to work fine on 1.7.10 as well. If you could give a _specific_ example of how to replicate the issue that would be much appreciated. Otherwise I will close this issue soon.

**Comment by CyborgShadow** [comment]
Go ahead and close it. I've not played 1.7 in quite some time now so I
forget exactly how to reproduce. I remember vaguely that it didn't work
unless I also had some other filter on the bag.
