### ISSUE TITLE
Backpacks don't render correctly in multiplayer

### ISSUE THREAD

**Issue by sblectric** [gr8pefish/IronBackpacks#56]
When in multiplayer, the backpacks of other players render glitchily in the position that they put them on in and don't disappear until the player takes the backpack off.

Screenshot:
![#1](https://cloud.githubusercontent.com/assets/14228556/13194216/26fc03d2-d757-11e5-8fca-f93d807529f3.png)

This screenshot shows that the object is indeed a backpack, as the shape is the same:
![#2](https://cloud.githubusercontent.com/assets/14228556/13194220/57f9eb98-d757-11e5-8c7a-8f3c273b02d1.png)

IronBackpacks version 1.8.9-2.0.5

**Comment by gr8pefish** [comment]
Version please?

**Comment by sblectric** [comment]
Ah yes, it's version 1.8.9-2.0.5.

**Comment by gr8pefish** [comment]
Yeah, I'm working on internally changing how the backpack is rendered, from it being an entity to just an extra model on the player. This is a decently large change (and I am swamped with schoolwork at the current moment) so it is taking a while, but I will eventually fix it.

**Comment by sblectric** [comment]
A quick workaround could be just to make it invisible to other players for the time being
