### ISSUE TITLE
Custom recipe limitations 

### ISSUE THREAD

**Issue by nmarshall23** [gr8pefish/IronBackpacks#58]
For the 1.7.10 version. 

When customizing the recipes, a itemName with a period is not read correctly. This will lead to a the game hanging on FML stage 5.

For example `items.Railcraft:part.rebar`

Here is the log output.
http://pastebin.com/p2dBwfr9

Also there is no way to specify an damage value. 

I'd suggest removing the recipes customization feature and supporting MineTweaker3. 

On that topic of MineTweaker3. When `recipes.removeShaped` is used to remove a backpack's recipe. I then can not apply upgrades. I suspect this is MineTweaker3 fault.

**Comment by gr8pefish** [comment]
Supporting minetweaker, the config recipes are long gone at this point.
