### ISSUE TITLE
Client crash when sneak right clicking backpack

### ISSUE THREAD

**Issue by bigtruckin78** [gr8pefish/IronBackpacks#59]
Game crashes when I sneak right click my diamond backpack with damage, depth, and advanced nesting upgrades installed. I'm using version 1.2.15 on MC 1.7.10 using forge 1558. I'm using Java 8u71.

Crash report: http://pastebin.com/xLZyDJzv
FML Log:  [fml-client-3.txt](https://github.com/gr8pefish/IronBackpacks/files/149207/fml-client-3.txt)

**Comment by gr8pefish** [comment]
Ah yes, this one was fixed as of v1.2.16.
