### ISSUE TITLE
Crashed when picking up thermal expansion cache

### ISSUE THREAD

**Issue by bigtruckin78** [gr8pefish/IronBackpacks#60]
I went to pick up a Thermal Expansion cache (<-- partially full)  I had wrenched loose and the game crashed. Now the game crashes whenever I try to launch that world. I looked at the crash report and it appears to be caused by Iron Backpacks. I'm running version 1.2.15 of your mod, Minecraft 1.7.10, and forge 1558. Java is version 8u71.

Crash report: https://paste.ee/p/PKiSb

**Comment by gr8pefish** [comment]
Paste link is gone, I waited too long. Issue needs to be closed because I can't replicate and have no log.
