### ISSUE TITLE
1.8 Version appears to be missing key commands

### ISSUE THREAD

**Issue by ChicknFarmerJohn** [gr8pefish/IronBackpacks#63]
The latest stable release 1.8-1.0.7 does not recognize the key commands to mount the backpack with Key_B, or opening with Key_R.  Possibly an oversight with the new config file?

**Comment by gr8pefish** [comment]
Have to move forward. 1.10 version is way better than the 1.8.9 one. I will come back and fix the error if I can, but I currently don't have the time to maintain 3 versions.
