### ISSUE TITLE
Crafting Table Crash

### ISSUE THREAD

**Issue by TechnologicApe** [gr8pefish/IronBackpacks#64]
I went to craft a backpack with an upgrade, but it crashed as soon as I clicked the upgrade into the table. I was using this in creative mode.

[crash-2016-03-16_22.12.14-client.txt](https://github.com/gr8pefish/IronBackpacks/files/177173/crash-2016-03-16_22.12.14-client.txt)

**Comment by gr8pefish** [comment]
I need more information to fix this.

What version of Minecraft? What mod version? What exactly happened? Be more specific.
I need the server crash log as well.

Thanks

**Comment by TechnologicApe** [comment]
Minecraft 1.7.10.
Most recent Iron Backpacks file.
I put the bag in a crafting table, I then went to pit an upgrade into the table with it. As soon as I clicked into the table,  the game froze and then closed itself.

http://pastebin.com/xeLmXwa3

**Comment by TechnologicApe** [comment]
Hello?

**Comment by TechnologicApe** [comment]
Is there a fix?

**Comment by gr8pefish** [comment]
Hey,

I'm a very busy guy. I'm a full-time student, and I only mod in my (scarce) spare time, and I do it entirely for free. This means it can't always be high on my list of priorities, and when other things pop up in my life, I have to attend to them first. Now, your bug has been noted and will be attended to when I can get to it, _but not before then_. Now, could you please stop pinging this thread?

Thanks.

**Comment by TechnologicApe** [comment]
I apologize. I had no idea. I will wait patiently.

**Comment by gr8pefish** [comment]
Hey dude/dudette, so sorry for snapping earlier (as in months ago). I love to mod, but, as I stated excessively clearly, can't commit dedicated time to it, and I was very stressed at the time you brought up this issue; I apologize for handling it poorly. Anyways, I have recently gotten some opportunity to pursue it again, so I am back to squashing bugs :)

In regards to the issue, it looks like it is actually not on my end; I think it was an old Forge bug. If you run into the error again (with updated versions of the relevant mods) feel free to make a new issue, as I am closing this one.

**Comment by TechnologicApe** [comment]
I completely understand. It's all good.
