### ISSUE TITLE
NPE when logging into RFTools Dismensions

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [gr8pefish/IronBackpacks#65]
Getting **NullPointerException** while wearing a backpack (Golden Storage Emphasis) while logging into an RFTools Dimension. See the Attached log file.
[fml-client-latest.log.txt](https://github.com/gr8pefish/IronBackpacks/files/190755/fml-client-latest.log.txt)

**Comment by McJty** [comment]
It is crashing in the ironbackpacks mod so I think you should report this to them

**Comment by McJty** [comment]
Can you try what happens if you go into nether or other dimensions? I don't see what RFTools could do that would cause this

**Comment by gr8pefish** [comment]
@McJty Pretty sure it's on my end, unless you aren't calling PlayerChangedDimensionEvent; it's an intermittent error that keeps cropping up. 

@Rumpelstiltskinny In the process of rewriting backpacks from entities to static model rendering, which should fix it. However, I don't know what I'm doing (which is fine, it just means more work/time), and I'm busy in school, so unfortunately it will probably take a while.

**Comment by Rumpelstiltskinny** [comment]
Thank you both for responding. Happy to hear that a fix may be in the works. (My current dubious work-around is to unequip the backpack (which **doesn't** pop into my inventory, incidentally) then teleport to the RF Dimension using the Matter Transmitter)

Anyhow, love your mods guys.
