### ISSUE TITLE
How to setup the source/project in Eclipse?

### ISSUE THREAD

**Issue by cemerson** [gr8pefish/IronBackpacks#66]
Anyone have steps on getting this source setup/imported as a project in Eclipse? I was going to try to get it built in 1.9 if possible ...

**Comment by TehNut** [comment]
1. Change [this](https://github.com/gr8pefish/IronBackpacks/blob/master-1.8.9/gradle.properties#L8) to 1.9
2. Change [this](https://github.com/gr8pefish/IronBackpacks/blob/master-1.8.9/gradle.properties#L9) to a valid 1.9 Forge version
3. Change [this](https://github.com/gr8pefish/IronBackpacks/blob/master-1.8.9/gradle.properties#L10) to a valid 1.9 JEI version
4. Run `gradlew setupDecompWorkspace eclipse` and import the `../eclipse/` folder into Eclipse.
5. Update everything to 1.9.
6. Run `gradlew build`.

**Comment by cemerson** [comment]
Thanks @TehNut - that's just the level of detail I need ... sadly I got stuck w/the gradlew command from errors/exceptions. I've brute-forced my way through a couple of them but just keep hitting wall - the latest being:  

`:recompileMc FAILED`
`FAILURE: Build failed with an exception.`
`* What went wrong:`
`Execution failed for task ':recompileMc'.`
`Compile failed; see the compiler error output for details.`

`* Exception is: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':recompi
leMc'. at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:69) ...`

Full log: http://pastebin.com/fimcDbq3 

Don't feel obliged to help me resolve this - but looks like I'm stuck for now on this.

**Comment by TehNut** [comment]
Whoops. Change `mappings_version` in `gradle.properties` to `snapshot_20160411`. The format of those snapshots are `snapshot_YEARMONTHDAY` and are built nightly. So if that one doesn't work, just try a few days prior.

**Comment by cemerson** [comment]
Thanks @TehNut  - that got me in and running in Eclipse. Sadly it looks like 1.9 support will take a fair amount of deprecated method renaming or changes so I think it's beyond my skills to rebuild on my own. I can handle the *.entity to *.getEntity() type stuff but there looks to be some more complicated stuff to fix on top of those so I'm going to stay out for now.

**Comment by cemerson** [comment]
Actually @TehNut I'm starting to wonder if my setup process jacked up something in the Eclipse project because way too many of the import statements claim they're now broken/missing (like below). I may try to rebuild the project and try again later. 

`import net.minecraft.client.resources.model.ModelBakery;`
`import net.minecraft.util.StatCollector;`

![screenshot_47](https://cloud.githubusercontent.com/assets/1080397/14496888/bf0cb920-0162-11e6-9e18-f4c8720afa9c.png)

**Comment by TehNut** [comment]
Nope that's correct. Lots of redactors were made by Mojang.

I can look at a quick'n'dirty 1.9 update in the next few days, if you'd like.

**Comment by cemerson** [comment]
Ah @TehNut - that explains it. I did a quick 1.9 rebuild for [roguelike dungeons](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290238-roguelike-dungeons-v1-4-5?comment=1287) but that only had like 3 (easy) quick fixes. But w/this mod there are WAY more things to fix - some are quick fix stuff but others get a bit into the weeds (for me) in that I can't figure out what the old methods/objects etc have been replaced with. Just for my own curiosity ... where do you go to find out that type of stuff?

**Comment by gr8pefish** [comment]
@cemerson I use IRC, the deobfuscated source code, other open source repositories, and lots of trial and error to update :P

Anyways, 1.10 alpha is out, so closing this issue. Thanks for trying to help (sincerely)!
