### ISSUE TITLE
IronBackpacks-1.7.10-1.2.15 ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by djvalley** [gr8pefish/IronBackpacks#69]
Getting this error after upgrading backpack to the void filter upgrade.
Tried remaking the backpack and using different filter blocks.
Regardless of if the item being picked up was on the list, the server would crash with the exception.
[crash-2016-05-19_11.03.49-server.txt](https://github.com/gr8pefish/IronBackpacks/files/272992/crash-2016-05-19_11.03.49-server.txt)

**Comment by gr8pefish** [comment]
Closed as of 1.2.16
