### ISSUE TITLE
[1.10.2] 2.1.0 Server crash

### ISSUE THREAD

**Issue by dirtyfargo** [gr8pefish/IronBackpacks#76]
Loads up fine on my client, but server side I get this [crash report](https://gist.github.com/dirtyfargo/b9f93f6814ac267739d436032f342c1a).
Version: 2.1.0
Forge: 12.18.1.2094

**Comment by gr8pefish** [comment]
Thanks, should be a fixed version up momentarily.

**Comment by gr8pefish** [comment]
Alright, it's up now.

**Comment by dirtyfargo** [comment]
Seems to be working great now, thanks =)

**Comment by gr8pefish** [comment]
Sweet! I forgot to test it on a server somehow, but that shouldn't happen again.

As always, good bug reports posted here on Github are most appreciated 👍 

Edit: FYI dimensions cause all sorts of errors if on a server, so no need to let me know that is an issue.

**Comment by dirtyfargo** [comment]
Sounds good :) Ooo alright I won't bring my new backpack to other dimensions just yet :P
