### ISSUE TITLE
[1.10] Fix backpacks misbehaving when changing dimensions on dedicated server

### ISSUE THREAD

**Issue by gr8pefish** [gr8pefish/IronBackpacks#77]
On my ToDo list, as the next item.

**Comment by Darkosto** [comment]
Thank you! I lost my backpack when coming back from the End :(

**Comment by gr8pefish** [comment]
Sorry to hear it; there's good reason as to why it is only an 'alpha' release on 1.10.

Rest assured that I am currently working on a fix though!

**Comment by Darkosto** [comment]
No worries though! I was about to post a report and saw you had it on your to-do list, so I thought I'd give ya a hard time :P 

I'm looking forward to using this mod in my new pack, thanks again for your hard work!
