### ISSUE TITLE
1.10.2 restock upgrade doesn't appear to function

### ISSUE THREAD

**Issue by LordHellscream** [gr8pefish/IronBackpacks#79]
Ver. 2.2.0

Repro:
put an arrow to one of the slot, then put 2 stacks of arrows to the backpack, leave a few arrows in the normal inventory, fire an arrow, restock doesnt happen.

**Comment by gr8pefish** [comment]
Ah, it should work, but just not for that specific action (shooting arrows). I will add that tomorrow.
