### ISSUE TITLE
1.10.2 soul bound enchantment(from ender io) doesn't show up on the backpack

### ISSUE THREAD

**Issue by LordHellscream** [gr8pefish/IronBackpacks#81]
BTW, just want to say this mod is AWESOME, the best thing happened to inventory management by FAR. keep up the great work!

Anyway, after the anvil crash was fixed, I tried adding the soulbound enchantment (Ender IO) to the backpack, it went through except that the backpack doesn't show it is getting that enchantment, and the enchantment doesn't do anything
However, when I tried to enchant (using the anvil) again with soulbound it wouldn't allow anymore (indicate that it is already have that enchantment)

The soulbound enchantment works on pretty much any items I've seen from any mod, its interesting it doesnt work with iron backpack

**Comment by TehNut** [comment]
It should not have been possible to apply it the first time. Backpacks are set to never provide anything in the output of an Anvil. I would suggest using the built-in Soulbound upgrade for Backpacks.

**Comment by gr8pefish** [comment]
Alright, I went through and fixed it, small oversight there, sorry. What I intended was that anvils are functionally useless with backpacks, which is the case now. Use the 'Eternity upgrade' if you want the backpack to persist through death. The 'Renaming upgrade' can be used to, unsurprisingly, rename the pack (if it is configured that way; it is automatically in by default).

Glad you enjoy it! I'm super open to any form of constructive feedback (e.g. balance tweaks/improvements/feature requests/annoyances/etc.), so please feel more than welcome to post them! I haven't had time to actually play with the mod yet, so, once again, good feedback is invaluable. Thanks!

**Comment by LordHellscream** [comment]
Eternal update is a little much consider the most priced items are usaully those equipped or on the action bar (magical armors and tools/weapons), and the stuff in the backpack are usually items you pick up along the way. "Insuring" the backpack and its content with bunch of emerald and diamonds for 1 death is a little steep
