### ISSUE TITLE
1.10.2 Nesting upgrade with a bag with filter update wouldn't pick up items

### ISSUE THREAD

**Issue by LordHellscream** [gr8pefish/IronBackpacks#82]
As i understand it, if you have a nesting upgrade on your main backpack (say a diamond bag), then have an iron backpack with a filter upgrade, then when you collect loot in that filter, it will go directly to the iron bag?
I have a rotten flesh listed in the iron backpack's filter, and place the iron backpack into the diamond backpack. 
but it doesn't pick up any rotten flesh (it goes straight to my inventory).

**Comment by gr8pefish** [comment]
You need the depth upgrade to make this work!

The nesting upgrade simply allows nesting, it doesn't account for nested _functionality_; that is where the depth upgrade comes in.

Any suggestions you have for making this more clear to future players are welcome!
