### ISSUE TITLE
Backpacks need to be opened normally once to function correctly.

### ISSUE THREAD

**Issue by gr8pefish** [gr8pefish/IronBackpacks#88]
#### Issue Description:

Backpack must be opened once via a normal right click in a hotbar slot before it can be used correctly. This is obviously not ideal.
#### What happens:

Backpack doesn't operate correctly. Deletes/dupes items, etc.
#### What you expected to happen:

Normal functionality like other backpacks.
#### Steps to reproduce (important):
1. Make any backpack, and don't open it.
2. Right click it from an inventory.
3. Watch as it doesn't update contents correctly.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- IronBackpacks: 1.10-all

**Comment by TehNut** [comment]
Should be solved as of rewrite.
