### ISSUE TITLE
Right clicking inside already open bag causes a crash

### ISSUE THREAD

**Issue by chuiu** [gr8pefish/IronBackpacks#89]
Whenever I try to right click within a bag to split a stack of something the game immediately crashes on me.
[crash-2016-10-23_18.26.30-client.txt](https://github.com/gr8pefish/IronBackpacks/files/546698/crash-2016-10-23_18.26.30-client.txt)

**Comment by chuiu** [comment]
I also just got a crash trying to move them with my mouse wheel using the item scroller mod.

[crash-2016-10-23_18.34.35-client.txt](https://github.com/gr8pefish/IronBackpacks/files/546701/crash-2016-10-23_18.34.35-client.txt)

**Comment by gr8pefish** [comment]
Yeah it's the same error. Do you have EnderStorage in the pack?

Edit: No you don't. I found the error; it's my bad. Fix should be up super soon.

**Comment by chuiu** [comment]
No I don't.  There is a full mod list in those crash logs.

**Comment by gr8pefish** [comment]
Sorry, that's one thing that isn't caught in my dev. environment. I'll push a version up in the next 10 minutes (just want to polish a couple textures real quick for the next version).
Edit: Will be up momentarily.

**Comment by gr8pefish** [comment]
Alright new version is up, should be fixed. Sorry about that!

**Comment by chuiu** [comment]
That was fast!  Thanks, its working great now!

**Comment by gr8pefish** [comment]
No problem :) 

Random aside: If you have any questions/comments/criticisms/suggestions about the mod I'd love to hear 'em! Good feedback is hard to come by.

**Comment by chuiu** [comment]
I do have a couple ideas actually.  One is obvious, ender backpack.  Unless I'm not seeing it somehow.

The other is tool slots.  Something like 5-6 slots that you can add to your backpack to store tools.  Then whenever you have a tool selected on your hotbar, you can shift + mouse wheel to scroll through tools you have stored in your backpack and swap them.

**Comment by TehNut** [comment]
I added an Ender Bag in my 1.8 port if you want to look at that, @gr8pefish
