### ISSUE TITLE
Trying to open the UI for one backpack from within another sometimes crashes the client

### ISSUE THREAD

**Issue by ribbanya** [gr8pefish/IronBackpacks#96]
#### Issue Description:
Trying to open either the inventory or the settings UI of one backpack while viewing the contents of another frequently results in an unhandled `IndexOutOfBoundsException`.

#### What happens:
Client crash log: http://hastebin.com/ujuvafuwud.txt

No server-side errors.

#### What you expected to happen:
The contents or settings UI of the second backpack to display as requested.

#### Steps to reproduce (important):

1. Have more than one backpack in inventory.
2. Right click or shift-right click another backpack.

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 2.2.9
- Minecraft: 1.10.2
- Forge: 12.18.2.2116
- [WyldLife](https://mods.curse.com/modpacks/minecraft/252521-wyldlife#t1:other-downloads) 1.2.2

**Comment by gr8pefish** [comment]
Hmm I can't seem to replicate this. Can you give me an exact example of what causes this? (e.g. open the inventory of a diamond backpack (upgrade emphasis) from an open basic backpack, or something along those lines). Thanks!

Also, to clarify, it crashes _precisely_ when you try to open it, correct? Not putting something in it, or something along those lines.

Also, has the config been changed in the modpack?

**Comment by ribbanya** [comment]
- IronBackpacks NBT data:

![image](http://i.imgur.com/kwjllfl.png)
(Not sure why the second `CAP` node is there; I don't even think that copy of `Miscellaneous` exists in-game.)
- Full playerdata: http://www.mediafire.com/file/bvki632pbiav8ig
- Config: http://hastebin.com/qofufiqojo.cfg

---

Opening the inventory of `Cheap Resources` and then attempting to open the inventory of `Miscellaneous`, which is next in player inventory, triggers the crash ([report](http://hastebin.com/ohihohokiv.txt)).

**Comment by ribbanya** [comment]
So, I transferred all my stuff (from my inventory and each backpack) into chests. Put both backpacks into my inventory, tried to reproduce the crash. Worked as intended, instead.

I put everything back into their original containers, sorted my inventory with InventoryTweaks to arrange it similarly to how it was, tried again to reproduce the bug. No crash.

olayerdata: http://www.mediafire.com/file/d5byxiwf584b2nx

**Comment by gr8pefish** [comment]
Alright, thanks for that. Unfortunately, I can't replicate it still. I manually copied over the upgrades and some other data (like what you had in the filters) from your backpack setup to mine in my development environment, but cannot make it crash.

Did it start happening after a specific point (like some upgrade added), or when the pack (i.e. this mod) was updated (and if so, what version), or did it seem to be at random? If I can't duplicate, the error code is specific enough I can try and push out some fixes for you that you can try until we get it to work.

Thanks.

Edit: Oh, just saw your comment, it just popped up. That is super strange. The crash report leads me to believe it is an error on my end, but I cannot for the life of me get it to do so on my own setup, which makes me think that it _might_ be an inter-mod issue.

**Comment by ribbanya** [comment]
It started happening after an update, yes. I'll let you know if it starts happening again.

If you downloaded the playerdata, you may want to redownload it. I had to rehost it because Dropbox overwrote the old version of the file when I uploaded the new one. Edited the links.

**Comment by ribbanya** [comment]
Okay, here's another crash report. Same playerdata as my previous post, all I did was open up one of the backpack's inventories and spam shift-right click on the others. I don't remember which backpack was open (because at that point I was assuming the issue had fixed itself).

http://hastebin.com/akereyitib.txt

Edit: Perhaps an issue with MouseTweaks? I'll verify.

**Comment by gr8pefish** [comment]
Okay, I dl'd your recent playerdata, I see no issues in there.

I'll dig into the issue on my code, as I still can't replicate (with a similar setup, spam shift-right clicking other packs, on a server). I'll update this once I make some progress.

**Comment by ribbanya** [comment]
It's MouseTweaks. Disabling its `Right Mouse Button Tweak` option fixes the issue.

Sorry for spinning your wheels.

**Comment by gr8pefish** [comment]
Ah thanks, I was getting a bit confused :) I'll make a note to work on it for future compat stuff though.

Thanks for the detailed reports by the way, would've been impossible to narrow down otherwise!
