### ISSUE TITLE
Add Hotbar Swap Upgrade

### ISSUE THREAD

**Issue by Alaberti** [gr8pefish/IronBackpacks#98]
The basic gist is to have a hotkey that swaps the gear on a player's hotbar with the first row of an equipped backpack. Thoughts?

**Comment by gr8pefish** [comment]
Yeah, this should be doable. That being said, I have some other things in my ToDo list that would take priority over this. One of which is internally reorganizing the way upgrades are added, so look for this to be added as a new upgrade in the future, but no time soon (perhaps when I do a small rewrite of the mod for 1.11).

**Comment by gr8pefish** [comment]
I'm actually going to keep this issue open, for the 1.11+ versions, as it's a solid idea and I'll forget about it otherwise.

**Comment by gr8pefish** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Hotbar Swap Upgrade](https://trello.com/c/kK42UlRO/44-add-hotbar-swap-upgrade)
